unit TestMathClass2;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, SysUtils, MathClass;

type
  // Test methods for class TMath

  TestTMath = class(TTestCase)
  strict private
    FMath: TMath;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestAdd;
    procedure TestDivide;
    procedure TestDivideByZero;
    procedure TestMultiply;
    procedure TestSubtract;
    procedure TestDoubleIt;
    procedure TestTruncate;
  end;

implementation

procedure TestTMath.SetUp;
begin
  FMath := TMath.Create;
end;

procedure TestTMath.TearDown;
begin
  FMath.Free;
  FMath := nil;
end;

procedure TestTMath.TestAdd;
begin
  // Rule 1.2.4.5
  FMath.Value := 50;
  FMath.Add(50);
  CheckEquals(100,FMath.Value);
  CheckNotEquals(50,FMath.Value);
end;

procedure TestTMath.TestDivide;
var
  Value: Double;
begin
  FMath.Value := 50;
  FMath.Divide(2);
  CheckEquals(25,FMath.Value);

  FMath.Value := 100;
  FMath.Divide(2);
  CheckEquals(50,FMath.Value);
end;

procedure TestTMath.TestDivideByZero;
begin
  ExpectedException := EZeroDivide;
  FMath.Value := 50;
  FMath.Divide(0);
end;

procedure TestTMath.TestMultiply;
var
  Value: Double;
begin
  // TODO: Setup method call parameters
  FMath.Multiply(Value);
  // TODO: Validate method results
end;

procedure TestTMath.TestSubtract;
var
  Value: Double;
begin
  // TODO: Setup method call parameters
  FMath.Subtract(Value);
  // TODO: Validate method results
end;

procedure TestTMath.TestDoubleIt;
begin
  FMath.DoubleIt;
  // TODO: Validate method results
end;

procedure TestTMath.TestTruncate;
begin
  FMath.Truncate;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTMath.Suite);
end.

