unit IPCThrdConst_WT1600;

interface

const
  MAX_CLIENTS        = 6;
  TIMEOUT            = 2000;
  BUFFER_NAME        = 'BUFFER_NAME_WT1600';
  BUFFER_MUTEX_NAME  = 'BUFFER_MUTEX_WT1600';
  MONITOR_EVENT_NAME = 'MONITOR_EVENT_WT1600';
  CLIENT_EVENT_NAME  = 'CLIENT_EVENT_WT1600';

implementation


end.
 