unit PIPE_Unit;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, Vcl.Imaging.pngimage, Vcl.ExtCtrls,
  AdvPageControl, Vcl.ComCtrls, AdvScrollBox, Vcl.Imaging.jpeg, AdvPanel,
  Vcl.StdCtrls, iLed, iLedArrow, iValve, iComponent, iVCLComponent,
  iCustomComponent, iPipe, iPipeJoint, JvExControls, JvLabel, iMotor,
  ShadowButton;

type
  TPipe_Frm = class(TForm)
    JvLabel56: TJvLabel;
    PIPE: TAdvPageControl;
    AdvTabSheet1: TAdvTabSheet;
    AdvScrollBox1: TAdvScrollBox;
    Shape92: TShape;
    Shape91: TShape;
    Shape99: TShape;
    Shape96: TShape;
    Shape88: TShape;
    Shape79: TShape;
    Shape93: TShape;
    Label52: TLabel;
    Shape87: TShape;
    Shape22: TShape;
    Shape37: TShape;
    Shape44: TShape;
    Shape45: TShape;
    Label32: TLabel;
    JvLabel2: TJvLabel;
    JvLabel3: TJvLabel;
    Label1: TLabel;
    Label2: TLabel;
    Label21: TLabel;
    Label24: TLabel;
    Label34: TLabel;
    Label39: TLabel;
    Label5: TLabel;
    Shape46: TShape;
    Shape47: TShape;
    Label36: TLabel;
    Shape31: TShape;
    Shape35: TShape;
    Label31: TLabel;
    Shape36: TShape;
    Shape40: TShape;
    Shape41: TShape;
    Shape38: TShape;
    Shape39: TShape;
    Shape42: TShape;
    Label30: TLabel;
    Label26: TLabel;
    Shape7: TShape;
    Shape29: TShape;
    Label27: TLabel;
    Shape32: TShape;
    Shape33: TShape;
    Label28: TLabel;
    Shape64: TShape;
    Label25: TLabel;
    Shape48: TShape;
    Shape65: TShape;
    Label29: TLabel;
    Shape66: TShape;
    Shape67: TShape;
    Label33: TLabel;
    Label35: TLabel;
    Shape50: TShape;
    Shape51: TShape;
    Shape53: TShape;
    Label45: TLabel;
    Shape54: TShape;
    JvLabel1: TJvLabel;
    JvLabel4: TJvLabel;
    Label7: TLabel;
    Shape1: TShape;
    Shape2: TShape;
    Label10: TLabel;
    Shape4: TShape;
    Shape5: TShape;
    Label11: TLabel;
    Shape6: TShape;
    Shape8: TShape;
    Shape9: TShape;
    Shape10: TShape;
    Shape13: TShape;
    Shape14: TShape;
    Label12: TLabel;
    Shape15: TShape;
    Shape16: TShape;
    Label13: TLabel;
    Label14: TLabel;
    Shape17: TShape;
    Shape18: TShape;
    Label15: TLabel;
    Shape19: TShape;
    Shape20: TShape;
    Label16: TLabel;
    Shape21: TShape;
    Label17: TLabel;
    Shape24: TShape;
    Shape25: TShape;
    Shape26: TShape;
    Shape27: TShape;
    Label18: TLabel;
    Shape28: TShape;
    Shape68: TShape;
    Label19: TLabel;
    Label20: TLabel;
    Shape3: TShape;
    Shape73: TShape;
    Label3: TLabel;
    Label4: TLabel;
    Label6: TLabel;
    Shape11: TShape;
    Shape55: TShape;
    Shape57: TShape;
    Label41: TLabel;
    Shape58: TShape;
    Label42: TLabel;
    Label43: TLabel;
    Label44: TLabel;
    JvLabel8: TJvLabel;
    Shape62: TShape;
    Shape63: TShape;
    Shape78: TShape;
    Label40: TLabel;
    Label46: TLabel;
    Shape81: TShape;
    Shape82: TShape;
    Label47: TLabel;
    Shape83: TShape;
    Shape84: TShape;
    Shape85: TShape;
    Shape86: TShape;
    Shape89: TShape;
    Shape90: TShape;
    Label50: TLabel;
    Label48: TLabel;
    Shape94: TShape;
    Shape95: TShape;
    Label49: TLabel;
    Label51: TLabel;
    Shape97: TShape;
    Shape98: TShape;
    Label53: TLabel;
    Label54: TLabel;
    Shape80: TShape;
    Shape100: TShape;
    Image1: TImage;
    Label55: TLabel;
    Label56: TLabel;
    Image2: TImage;
    Label57: TLabel;
    Label58: TLabel;
    Shape107: TShape;
    Label59: TLabel;
    JvLabel19: TJvLabel;
    JvLabel20: TJvLabel;
    JvLabel21: TJvLabel;
    JvLabel22: TJvLabel;
    Shape56: TShape;
    Shape59: TShape;
    Shape60: TShape;
    Shape61: TShape;
    Label9: TLabel;
    Label22: TLabel;
    Label23: TLabel;
    Label38: TLabel;
    JvLabel5: TJvLabel;
    Shape75: TShape;
    Shape76: TShape;
    Shape30: TShape;
    Shape34: TShape;
    Shape43: TShape;
    Shape49: TShape;
    Label8: TLabel;
    Shape69: TShape;
    Shape70: TShape;
    Shape71: TShape;
    Label37: TLabel;
    Shape72: TShape;
    Shape74: TShape;
    JvLabel182: TJvLabel;
    JvLabel183: TJvLabel;
    JvLabel184: TJvLabel;
    JvLabel185: TJvLabel;
    JvLabel186: TJvLabel;
    JvLabel187: TJvLabel;
    JvLabel188: TJvLabel;
    JvLabel189: TJvLabel;
    JvLabel190: TJvLabel;
    JvLabel191: TJvLabel;
    JvLabel33: TJvLabel;
    JvLabel42: TJvLabel;
    JvLabel192: TJvLabel;
    JvLabel193: TJvLabel;
    JvLabel194: TJvLabel;
    JvLabel195: TJvLabel;
    JvLabel196: TJvLabel;
    JvLabel197: TJvLabel;
    Label284: TLabel;
    Label285: TLabel;
    JvLabel213: TJvLabel;
    JvLabel214: TJvLabel;
    JvLabel215: TJvLabel;
    JvLabel216: TJvLabel;
    JvLabel217: TJvLabel;
    JvLabel218: TJvLabel;
    iPipe5: TiPipe;
    iPipe123: TiPipe;
    iLedArrow1: TiLedArrow;
    iPipe75: TiPipe;
    iPipe23: TiPipe;
    iPipe27: TiPipe;
    iPipe33: TiPipe;
    iPipe34: TiPipe;
    iPipe35: TiPipe;
    iPipe49: TiPipe;
    iPipe50: TiPipe;
    iPipe54: TiPipe;
    iValve17: TiValve;
    Panel1: TPanel;
    iValve24: TiValve;
    iPipe38: TiPipe;
    iPipe40: TiPipe;
    iValve15: TiValve;
    iPipe45: TiPipe;
    iPipe46: TiPipe;
    iPipe36: TiPipe;
    iPipe37: TiPipe;
    iValve14: TiValve;
    iPipe39: TiPipe;
    iPipe43: TiPipe;
    iPipe44: TiPipe;
    iLedArrow5: TiLedArrow;
    iPipe53: TiPipe;
    iPipe92: TiPipe;
    iValve23: TiValve;
    iPipe94: TiPipe;
    iPipe95: TiPipe;
    iPipe96: TiPipe;
    iPipe97: TiPipe;
    iPipe98: TiPipe;
    iValve20: TiValve;
    iValve18: TiValve;
    iLedArrow9: TiLedArrow;
    iValve19: TiValve;
    iPipe1: TiPipe;
    iPipe2: TiPipe;
    iPipe3: TiPipe;
    iPipe4: TiPipe;
    iPipe8: TiPipe;
    iPipe9: TiPipe;
    iValve2: TiValve;
    Panel2: TPanel;
    iValve3: TiValve;
    iPipe14: TiPipe;
    iPipe15: TiPipe;
    iValve4: TiValve;
    iPipe16: TiPipe;
    iValve5: TiValve;
    iPipe17: TiPipe;
    iPipe18: TiPipe;
    iPipe19: TiPipe;
    iPipe24: TiPipe;
    iPipe25: TiPipe;
    iValve6: TiValve;
    iValve7: TiValve;
    iPipe31: TiPipe;
    iPipe100: TiPipe;
    iValve8: TiValve;
    iPipe101: TiPipe;
    iPipe102: TiPipe;
    iPipe104: TiPipe;
    iPipe105: TiPipe;
    iPipe20: TiPipe;
    iPipe106: TiPipe;
    iPipe111: TiPipe;
    iPipe28: TiPipe;
    iValve1: TiValve;
    iPipe114: TiPipe;
    iPipe115: TiPipe;
    iPipe116: TiPipe;
    iPipe62: TiPipe;
    iValve27: TiValve;
    iPipe63: TiPipe;
    iPipe64: TiPipe;
    iLedArrow2: TiLedArrow;
    iPipe65: TiPipe;
    iPipe66: TiPipe;
    iPipe67: TiPipe;
    iPipe68: TiPipe;
    iPipe69: TiPipe;
    iValve29: TiValve;
    iValve30: TiValve;
    iPipe71: TiPipe;
    iPipe72: TiPipe;
    iPipe73: TiPipe;
    iPipe74: TiPipe;
    iValve32: TiValve;
    iValve33: TiValve;
    iPipe76: TiPipe;
    iValve35: TiValve;
    iPipe77: TiPipe;
    iPipe78: TiPipe;
    iPipe79: TiPipe;
    AdvPanel5: TAdvPanel;
    JvLabel15: TJvLabel;
    JvLabel16: TJvLabel;
    AdvPanel6: TAdvPanel;
    JvLabel17: TJvLabel;
    JvLabel18: TJvLabel;
    iPipe61: TiPipe;
    iPipe70: TiPipe;
    iPipe80: TiPipe;
    iPipe81: TiPipe;
    iLedArrow7: TiLedArrow;
    iValve36: TiValve;
    iPipe82: TiPipe;
    iPipe83: TiPipe;
    iPipe84: TiPipe;
    iPipe86: TiPipe;
    iPipe602: TiPipe;
    iPipe90: TiPipe;
    iValve38: TiValve;
    iPipe130: TiPipe;
    iPipe132: TiPipe;
    iPipe133: TiPipe;
    iPipe134: TiPipe;
    iPipe600: TiPipe;
    iPipe136: TiPipe;
    iPipe137: TiPipe;
    iPipe601: TiPipe;
    iValve39: TiValve;
    iPipe140: TiPipe;
    iPipe141: TiPipe;
    iPipe143: TiPipe;
    iPipe144: TiPipe;
    iPipe145: TiPipe;
    iPipe900: TiPipe;
    iPipe149: TiPipe;
    iPipe151: TiPipe;
    iValve50: TiValve;
    iPipe152: TiPipe;
    iPipe150: TiPipe;
    iPipe153: TiPipe;
    iPipe154: TiPipe;
    iValve51: TiValve;
    iPipe800: TiPipe;
    iPipe156: TiPipe;
    iPipe502: TiPipe;
    iLedArrow13: TiLedArrow;
    iValve52: TiValve;
    iPipe501: TiPipe;
    iLedArrow14: TiLedArrow;
    iValve53: TiValve;
    iPipe500: TiPipe;
    iLedArrow15: TiLedArrow;
    iValve54: TiValve;
    iPipe160: TiPipe;
    iLedArrow16: TiLedArrow;
    iValve55: TiValve;
    iPipe161: TiPipe;
    iLedArrow17: TiLedArrow;
    iValve56: TiValve;
    iPipe162: TiPipe;
    iLedArrow18: TiLedArrow;
    iValve57: TiValve;
    iPipe99: TiPipe;
    iPipe163: TiPipe;
    iPipe117: TiPipe;
    iValve41: TiValve;
    iPipe148: TiPipe;
    iValve42: TiValve;
    iPipeJoint7: TiPipeJoint;
    iPipeJoint8: TiPipeJoint;
    iPipeJoint9: TiPipeJoint;
    iPipeJoint10: TiPipeJoint;
    iPipe52: TiPipe;
    iLedArrow12: TiLedArrow;
    iValve37: TiValve;
    iPipe85: TiPipe;
    iPipe88: TiPipe;
    iPipe89: TiPipe;
    iPipeJoint11: TiPipeJoint;
    iValve34: TiValve;
    iValve58: TiValve;
    iValve28: TiValve;
    iPipe21: TiPipe;
    iPipe55: TiPipe;
    iPipe56: TiPipe;
    iPipe57: TiPipe;
    iPipe58: TiPipe;
    iPipe59: TiPipe;
    iPipe60: TiPipe;
    iPipe91: TiPipe;
    iPipe93: TiPipe;
    iValve26: TiValve;
    iValve31: TiValve;
    iPipe119: TiPipe;
    iValve44: TiValve;
    iPipe120: TiPipe;
    iPipe121: TiPipe;
    iPipe122: TiPipe;
    AdvPanel1: TAdvPanel;
    JvLabel6: TJvLabel;
    JvLabel7: TJvLabel;
    AdvPanel4: TAdvPanel;
    JvLabel9: TJvLabel;
    JvLabel10: TJvLabel;
    iValve45: TiValve;
    iValve46: TiValve;
    iValve11: TiValve;
    iValve25: TiValve;
    iValve47: TiValve;
    iValve48: TiValve;
    iPipeJoint13: TiPipeJoint;
    iPipeJoint14: TiPipeJoint;
    iPipeJoint15: TiPipeJoint;
    iPipe87: TiPipe;
    iPipeJoint16: TiPipeJoint;
    iPipe124: TiPipe;
    iPipe125: TiPipe;
    iValve40: TiValve;
    iPipeJoint18: TiPipeJoint;
    iPipe108: TiPipe;
    iValve49: TiValve;
    iPipe109: TiPipe;
    iPipe22: TiPipe;
    iValve13: TiValve;
    iPipeJoint19: TiPipeJoint;
    iPipeJoint20: TiPipeJoint;
    iPipeJoint21: TiPipeJoint;
    iPipe32: TiPipe;
    iValve16: TiValve;
    iPipe41: TiPipe;
    iPipe42: TiPipe;
    iLedArrow19: TiLedArrow;
    iPipeJoint22: TiPipeJoint;
    iPipeJoint23: TiPipeJoint;
    iPipe6: TiPipe;
    iPipe7: TiPipe;
    iPipe118: TiPipe;
    iValve10: TiValve;
    iValve12: TiValve;
    iLedArrow8: TiLedArrow;
    iValve21: TiValve;
    iPipe126: TiPipe;
    iPipe127: TiPipe;
    iPipe128: TiPipe;
    iPipeJoint25: TiPipeJoint;
    iPipe10: TiPipe;
    iValve9: TiValve;
    iPipeJoint24: TiPipeJoint;
    iPipe112: TiPipe;
    iLedArrow10: TiLedArrow;
    iValve22: TiValve;
    iPipeJoint26: TiPipeJoint;
    iPipeJoint27: TiPipeJoint;
    iPipeJoint28: TiPipeJoint;
    iPipeJoint37: TiPipeJoint;
    iPipeJoint38: TiPipeJoint;
    iPipeJoint39: TiPipeJoint;
    iPipeJoint40: TiPipeJoint;
    iLedArrow11: TiLedArrow;
    iLedArrow21: TiLedArrow;
    iPipe11: TiPipe;
    iPipe12: TiPipe;
    iLedArrow3: TiLedArrow;
    iPipe13: TiPipe;
    iLedArrow4: TiLedArrow;
    iLedArrow6: TiLedArrow;
    iPipe26: TiPipe;
    iPipe29: TiPipe;
    iLedArrow22: TiLedArrow;
    iPipe30: TiPipe;
    iLedArrow23: TiLedArrow;
    iLedArrow24: TiLedArrow;
    iPipe47: TiPipe;
    iPipe48: TiPipe;
    iLedArrow25: TiLedArrow;
    iPipe51: TiPipe;
    iLedArrow26: TiLedArrow;
    iLedArrow30: TiLedArrow;
    iPipeJoint36: TiPipeJoint;
    iPipe774: TiPipe;
    iPipeJoint17: TiPipeJoint;
    iPipeJoint6: TiPipeJoint;
    iPipeJoint12: TiPipeJoint;
    iPipe772: TiPipe;
    Button1: TButton;
    Button2: TButton;
    Button3: TButton;
    Button4: TButton;
    Button5: TButton;
    Button6: TButton;
    Panel5: TPanel;
    Label288: TLabel;
    Label289: TLabel;
    Panel6: TPanel;
    Label290: TLabel;
    Label291: TLabel;
    Button7: TButton;
    iPipe803: TiPipe;
    iPipe804: TiPipe;
    AdvTabSheet2: TAdvTabSheet;
    AdvScrollBox2: TAdvScrollBox;
    Shape23: TShape;
    Shape101: TShape;
    JvLabel11: TJvLabel;
    Shape109: TShape;
    Shape111: TShape;
    Label60: TLabel;
    Label61: TLabel;
    Label62: TLabel;
    Label63: TLabel;
    Label64: TLabel;
    Label65: TLabel;
    Shape112: TShape;
    Shape113: TShape;
    Shape114: TShape;
    Shape115: TShape;
    Shape116: TShape;
    Shape117: TShape;
    Label66: TLabel;
    Label67: TLabel;
    Shape118: TShape;
    Shape119: TShape;
    Label68: TLabel;
    Label69: TLabel;
    Label70: TLabel;
    JvLabel12: TJvLabel;
    JvLabel13: TJvLabel;
    JvLabel14: TJvLabel;
    JvLabel23: TJvLabel;
    JvLabel25: TJvLabel;
    Label71: TLabel;
    Shape120: TShape;
    Label72: TLabel;
    Shape121: TShape;
    Label73: TLabel;
    Shape122: TShape;
    Shape123: TShape;
    Label74: TLabel;
    JvLabel26: TJvLabel;
    Label75: TLabel;
    Shape124: TShape;
    Shape125: TShape;
    Label76: TLabel;
    Shape126: TShape;
    Shape127: TShape;
    Shape128: TShape;
    Shape129: TShape;
    Shape130: TShape;
    Label77: TLabel;
    Label78: TLabel;
    Shape131: TShape;
    Label79: TLabel;
    Label80: TLabel;
    Label81: TLabel;
    Label82: TLabel;
    Label83: TLabel;
    Shape132: TShape;
    Label84: TLabel;
    Label85: TLabel;
    Shape133: TShape;
    Shape134: TShape;
    Shape135: TShape;
    Shape136: TShape;
    Label86: TLabel;
    Shape137: TShape;
    Shape138: TShape;
    Label87: TLabel;
    Label88: TLabel;
    Shape139: TShape;
    Shape140: TShape;
    Label89: TLabel;
    Shape141: TShape;
    Shape142: TShape;
    Shape143: TShape;
    Shape144: TShape;
    Shape145: TShape;
    Label90: TLabel;
    Label91: TLabel;
    Shape146: TShape;
    Shape147: TShape;
    Shape148: TShape;
    Shape149: TShape;
    Label92: TLabel;
    JvLabel27: TJvLabel;
    Shape150: TShape;
    Label93: TLabel;
    Label94: TLabel;
    Shape151: TShape;
    Shape152: TShape;
    Label95: TLabel;
    Shape153: TShape;
    Label96: TLabel;
    Shape154: TShape;
    Label97: TLabel;
    Shape155: TShape;
    Label98: TLabel;
    Label99: TLabel;
    Label100: TLabel;
    Shape156: TShape;
    JvLabel28: TJvLabel;
    Shape157: TShape;
    Shape158: TShape;
    Label101: TLabel;
    JvLabel29: TJvLabel;
    Label102: TLabel;
    Shape159: TShape;
    Shape160: TShape;
    Label103: TLabel;
    Shape161: TShape;
    Shape162: TShape;
    Shape163: TShape;
    Shape164: TShape;
    Shape165: TShape;
    Label104: TLabel;
    Label105: TLabel;
    Shape166: TShape;
    Shape167: TShape;
    Shape168: TShape;
    Shape169: TShape;
    Label106: TLabel;
    Shape170: TShape;
    Shape171: TShape;
    Label107: TLabel;
    Label108: TLabel;
    Shape172: TShape;
    Shape173: TShape;
    Label109: TLabel;
    Shape174: TShape;
    Shape175: TShape;
    Shape176: TShape;
    Shape177: TShape;
    Shape178: TShape;
    Label110: TLabel;
    Label111: TLabel;
    Shape179: TShape;
    Shape180: TShape;
    Shape181: TShape;
    Shape182: TShape;
    Label112: TLabel;
    JvLabel31: TJvLabel;
    Shape183: TShape;
    Label113: TLabel;
    Label114: TLabel;
    Shape184: TShape;
    Shape185: TShape;
    Label115: TLabel;
    Shape186: TShape;
    Label116: TLabel;
    Shape187: TShape;
    Label117: TLabel;
    Shape188: TShape;
    Label118: TLabel;
    JvLabel32: TJvLabel;
    Shape189: TShape;
    Shape190: TShape;
    Label119: TLabel;
    JvLabel34: TJvLabel;
    Label120: TLabel;
    Shape191: TShape;
    Shape192: TShape;
    Label121: TLabel;
    Shape193: TShape;
    Shape194: TShape;
    Shape195: TShape;
    Shape196: TShape;
    Shape197: TShape;
    Label122: TLabel;
    Label123: TLabel;
    Shape198: TShape;
    Shape199: TShape;
    Shape200: TShape;
    Shape201: TShape;
    Label124: TLabel;
    Shape202: TShape;
    Shape203: TShape;
    Label125: TLabel;
    Label126: TLabel;
    Shape204: TShape;
    Shape205: TShape;
    Label127: TLabel;
    Shape206: TShape;
    Shape207: TShape;
    Shape208: TShape;
    Shape209: TShape;
    Shape210: TShape;
    Label128: TLabel;
    Label129: TLabel;
    Shape211: TShape;
    Shape212: TShape;
    Shape213: TShape;
    Shape214: TShape;
    Label130: TLabel;
    JvLabel35: TJvLabel;
    Shape215: TShape;
    Label131: TLabel;
    Label132: TLabel;
    Shape216: TShape;
    Shape217: TShape;
    Label133: TLabel;
    Shape218: TShape;
    Label134: TLabel;
    Shape219: TShape;
    Label135: TLabel;
    Shape220: TShape;
    Label136: TLabel;
    JvLabel36: TJvLabel;
    Label137: TLabel;
    Label138: TLabel;
    Label139: TLabel;
    Label140: TLabel;
    Label141: TLabel;
    JvLabel37: TJvLabel;
    Label142: TLabel;
    Label143: TLabel;
    JvLabel38: TJvLabel;
    Shape221: TShape;
    JvLabel39: TJvLabel;
    Shape222: TShape;
    Label144: TLabel;
    JvLabel40: TJvLabel;
    JvLabel41: TJvLabel;
    JvLabel43: TJvLabel;
    JvLabel44: TJvLabel;
    Shape223: TShape;
    Shape224: TShape;
    JvLabel45: TJvLabel;
    Shape225: TShape;
    Label145: TLabel;
    Shape226: TShape;
    Label146: TLabel;
    JvLabel46: TJvLabel;
    Label147: TLabel;
    Label148: TLabel;
    Shape227: TShape;
    Shape228: TShape;
    Shape229: TShape;
    Shape230: TShape;
    Shape231: TShape;
    Shape232: TShape;
    Label149: TLabel;
    Label150: TLabel;
    Shape233: TShape;
    Shape234: TShape;
    Label151: TLabel;
    Label152: TLabel;
    Label153: TLabel;
    JvLabel47: TJvLabel;
    Shape235: TShape;
    JvLabel48: TJvLabel;
    Shape236: TShape;
    Label154: TLabel;
    JvLabel49: TJvLabel;
    JvLabel50: TJvLabel;
    Shape237: TShape;
    Shape238: TShape;
    JvLabel51: TJvLabel;
    JvLabel52: TJvLabel;
    JvLabel53: TJvLabel;
    Shape239: TShape;
    JvLabel54: TJvLabel;
    Shape240: TShape;
    JvLabel55: TJvLabel;
    JvLabel57: TJvLabel;
    JvLabel58: TJvLabel;
    JvLabel59: TJvLabel;
    JvLabel60: TJvLabel;
    Label155: TLabel;
    JvLabel61: TJvLabel;
    JvLabel62: TJvLabel;
    JvLabel63: TJvLabel;
    JvLabel64: TJvLabel;
    JvLabel65: TJvLabel;
    JvLabel66: TJvLabel;
    JvLabel67: TJvLabel;
    JvLabel68: TJvLabel;
    JvLabel69: TJvLabel;
    JvLabel70: TJvLabel;
    JvLabel71: TJvLabel;
    JvLabel72: TJvLabel;
    Shape241: TShape;
    Label156: TLabel;
    Shape242: TShape;
    JvLabel73: TJvLabel;
    JvLabel74: TJvLabel;
    JvLabel75: TJvLabel;
    JvLabel76: TJvLabel;
    JvLabel77: TJvLabel;
    JvLabel78: TJvLabel;
    Shape243: TShape;
    JvLabel79: TJvLabel;
    JvLabel80: TJvLabel;
    JvLabel81: TJvLabel;
    JvLabel82: TJvLabel;
    JvLabel83: TJvLabel;
    JvLabel84: TJvLabel;
    Shape244: TShape;
    Label157: TLabel;
    JvLabel85: TJvLabel;
    JvLabel86: TJvLabel;
    JvLabel87: TJvLabel;
    Label256: TLabel;
    Label257: TLabel;
    JvLabel88: TJvLabel;
    JvLabel89: TJvLabel;
    JvLabel90: TJvLabel;
    JvLabel91: TJvLabel;
    JvLabel92: TJvLabel;
    JvLabel93: TJvLabel;
    JvLabel94: TJvLabel;
    JvLabel95: TJvLabel;
    JvLabel96: TJvLabel;
    JvLabel97: TJvLabel;
    iPipe103: TiPipe;
    iPipe107: TiPipe;
    iPipe110: TiPipe;
    iPipe113: TiPipe;
    iPipe129: TiPipe;
    iValve43: TiValve;
    iPipe131: TiPipe;
    iPipe135: TiPipe;
    iValve59: TiValve;
    iPipe138: TiPipe;
    iValve60: TiValve;
    iPipe139: TiPipe;
    iValve61: TiValve;
    iPipe142: TiPipe;
    iPipe146: TiPipe;
    iPipe147: TiPipe;
    iValve62: TiValve;
    iValve63: TiValve;
    iValve64: TiValve;
    iPipe155: TiPipe;
    AdvPanel7: TAdvPanel;
    JvLabel98: TJvLabel;
    JvLabel99: TJvLabel;
    AdvPanel8: TAdvPanel;
    JvLabel100: TJvLabel;
    JvLabel101: TJvLabel;
    AdvPanel9: TAdvPanel;
    JvLabel102: TJvLabel;
    iPipe157: TiPipe;
    iPipe158: TiPipe;
    iPipe159: TiPipe;
    iPipe164: TiPipe;
    iPipe165: TiPipe;
    iPipe166: TiPipe;
    iPipe167: TiPipe;
    iValve65: TiValve;
    iPipe168: TiPipe;
    iLedArrow20: TiLedArrow;
    iPipe169: TiPipe;
    iValve66: TiValve;
    iPipe170: TiPipe;
    iPipe171: TiPipe;
    iPipe172: TiPipe;
    iPipe173: TiPipe;
    iPipe174: TiPipe;
    iValve67: TiValve;
    iValve68: TiValve;
    iValve69: TiValve;
    iValve70: TiValve;
    iValve71: TiValve;
    iPipe175: TiPipe;
    iPipe176: TiPipe;
    iPipe177: TiPipe;
    iPipe178: TiPipe;
    iPipe179: TiPipe;
    iPipe180: TiPipe;
    Panel3: TPanel;
    iValve72: TiValve;
    iPipe181: TiPipe;
    iPipe182: TiPipe;
    iPipe183: TiPipe;
    iPipe184: TiPipe;
    iPipe185: TiPipe;
    iPipe186: TiPipe;
    iPipe187: TiPipe;
    iLedArrow27: TiLedArrow;
    iLedArrow28: TiLedArrow;
    iValve73: TiValve;
    iPipe188: TiPipe;
    iPipe189: TiPipe;
    AdvPanel10: TAdvPanel;
    iPipe190: TiPipe;
    iPipe191: TiPipe;
    iPipe192: TiPipe;
    iPipe193: TiPipe;
    iPipe194: TiPipe;
    iPipe195: TiPipe;
    iPipe196: TiPipe;
    AdvPanel11: TAdvPanel;
    iPipe197: TiPipe;
    iPipe198: TiPipe;
    iPipe199: TiPipe;
    iPipe200: TiPipe;
    iPipe201: TiPipe;
    iPipe202: TiPipe;
    iLedArrow29: TiLedArrow;
    iPipe203: TiPipe;
    iPipe204: TiPipe;
    iValve74: TiValve;
    iPipe205: TiPipe;
    iPipe206: TiPipe;
    iPipe207: TiPipe;
    iPipe208: TiPipe;
    iPipe209: TiPipe;
    iValve75: TiValve;
    iPipe210: TiPipe;
    iPipe211: TiPipe;
    iValve77: TiValve;
    iPipe212: TiPipe;
    iPipe213: TiPipe;
    iPipe214: TiPipe;
    iPipe215: TiPipe;
    iPipe216: TiPipe;
    iPipe217: TiPipe;
    iPipe218: TiPipe;
    iLedArrow31: TiLedArrow;
    iLedArrow32: TiLedArrow;
    iValve78: TiValve;
    iPipe219: TiPipe;
    iPipe220: TiPipe;
    iLedArrow33: TiLedArrow;
    iPipe221: TiPipe;
    iPipe222: TiPipe;
    iValve79: TiValve;
    iPipe223: TiPipe;
    iPipe224: TiPipe;
    iPipe225: TiPipe;
    iPipe226: TiPipe;
    iPipe227: TiPipe;
    iValve80: TiValve;
    iLedArrow34: TiLedArrow;
    iLedArrow35: TiLedArrow;
    iLedArrow36: TiLedArrow;
    iLedArrow37: TiLedArrow;
    iLedArrow38: TiLedArrow;
    iValve81: TiValve;
    iValve84: TiValve;
    iValve86: TiValve;
    iPipe228: TiPipe;
    iPipe229: TiPipe;
    iPipe230: TiPipe;
    iValve87: TiValve;
    iPipe231: TiPipe;
    iPipe232: TiPipe;
    iPipe233: TiPipe;
    iPipe234: TiPipe;
    iValve88: TiValve;
    iPipe235: TiPipe;
    iPipe236: TiPipe;
    AdvPanel13: TAdvPanel;
    iPipe237: TiPipe;
    iPipe238: TiPipe;
    AdvPanel14: TAdvPanel;
    iPipe239: TiPipe;
    AdvPanel15: TAdvPanel;
    iValve89: TiValve;
    iValve90: TiValve;
    iPipe240: TiPipe;
    iPipe241: TiPipe;
    iPipe242: TiPipe;
    iPipe243: TiPipe;
    iPipe244: TiPipe;
    iPipe245: TiPipe;
    iValve91: TiValve;
    iPipe246: TiPipe;
    iValve93: TiValve;
    iPipe247: TiPipe;
    iPipe248: TiPipe;
    iPipe249: TiPipe;
    iPipe250: TiPipe;
    iValve94: TiValve;
    iPipe251: TiPipe;
    iPipe252: TiPipe;
    iPipe253: TiPipe;
    iPipe254: TiPipe;
    iPipe255: TiPipe;
    iPipe256: TiPipe;
    iPipe257: TiPipe;
    iLedArrow39: TiLedArrow;
    iLedArrow40: TiLedArrow;
    iValve95: TiValve;
    iPipe258: TiPipe;
    iPipe259: TiPipe;
    iPipe260: TiPipe;
    iLedArrow41: TiLedArrow;
    iPipe261: TiPipe;
    iPipe262: TiPipe;
    iValve96: TiValve;
    iPipe263: TiPipe;
    iPipe264: TiPipe;
    iPipe265: TiPipe;
    iPipe266: TiPipe;
    iPipe267: TiPipe;
    iValve97: TiValve;
    iPipe268: TiPipe;
    iPipe269: TiPipe;
    iValve98: TiValve;
    iPipe270: TiPipe;
    iPipe271: TiPipe;
    iPipe272: TiPipe;
    iPipe273: TiPipe;
    iPipe274: TiPipe;
    iPipe275: TiPipe;
    iPipe276: TiPipe;
    iLedArrow42: TiLedArrow;
    iLedArrow43: TiLedArrow;
    iValve99: TiValve;
    iPipe277: TiPipe;
    iPipe278: TiPipe;
    iLedArrow44: TiLedArrow;
    iPipe279: TiPipe;
    iPipe280: TiPipe;
    iValve100: TiValve;
    iPipe281: TiPipe;
    iPipe282: TiPipe;
    iPipe283: TiPipe;
    iPipe284: TiPipe;
    iPipe285: TiPipe;
    iValve101: TiValve;
    iLedArrow45: TiLedArrow;
    iLedArrow46: TiLedArrow;
    iLedArrow47: TiLedArrow;
    iLedArrow48: TiLedArrow;
    iLedArrow49: TiLedArrow;
    iValve102: TiValve;
    iValve103: TiValve;
    iValve104: TiValve;
    iPipe286: TiPipe;
    iPipe287: TiPipe;
    iPipe288: TiPipe;
    iValve105: TiValve;
    iPipe289: TiPipe;
    iPipe290: TiPipe;
    iPipe291: TiPipe;
    iPipe292: TiPipe;
    iValve106: TiValve;
    iPipe293: TiPipe;
    iPipe294: TiPipe;
    AdvPanel16: TAdvPanel;
    iPipe295: TiPipe;
    iValve107: TiValve;
    iPipe296: TiPipe;
    iValve108: TiValve;
    iPipe297: TiPipe;
    iPipe298: TiPipe;
    iPipe299: TiPipe;
    iValve109: TiValve;
    iPipe300: TiPipe;
    iPipe301: TiPipe;
    iPipe302: TiPipe;
    iPipe303: TiPipe;
    iPipe304: TiPipe;
    iPipe305: TiPipe;
    iPipe306: TiPipe;
    iLedArrow50: TiLedArrow;
    iLedArrow51: TiLedArrow;
    iValve110: TiValve;
    iPipe307: TiPipe;
    iPipe308: TiPipe;
    iLedArrow52: TiLedArrow;
    iPipe309: TiPipe;
    iPipe310: TiPipe;
    iValve111: TiValve;
    iPipe311: TiPipe;
    iPipe312: TiPipe;
    iPipe313: TiPipe;
    iPipe314: TiPipe;
    iPipe315: TiPipe;
    iValve112: TiValve;
    iPipe316: TiPipe;
    iPipe317: TiPipe;
    iValve113: TiValve;
    iPipe318: TiPipe;
    iPipe319: TiPipe;
    iPipe320: TiPipe;
    iPipe321: TiPipe;
    iPipe322: TiPipe;
    iPipe323: TiPipe;
    iPipe324: TiPipe;
    iLedArrow53: TiLedArrow;
    iLedArrow54: TiLedArrow;
    iValve114: TiValve;
    iPipe325: TiPipe;
    iPipe326: TiPipe;
    iLedArrow55: TiLedArrow;
    iPipe327: TiPipe;
    iPipe328: TiPipe;
    iValve115: TiValve;
    iPipe329: TiPipe;
    iPipe330: TiPipe;
    iPipe331: TiPipe;
    iPipe332: TiPipe;
    iPipe333: TiPipe;
    iValve116: TiValve;
    iLedArrow56: TiLedArrow;
    iLedArrow57: TiLedArrow;
    iLedArrow58: TiLedArrow;
    iLedArrow59: TiLedArrow;
    iLedArrow60: TiLedArrow;
    iValve117: TiValve;
    iValve118: TiValve;
    iValve119: TiValve;
    iPipe334: TiPipe;
    iPipe335: TiPipe;
    iPipe336: TiPipe;
    iValve120: TiValve;
    iPipe337: TiPipe;
    iPipe338: TiPipe;
    iPipe339: TiPipe;
    iPipe340: TiPipe;
    iValve121: TiValve;
    AdvPanel17: TAdvPanel;
    iPipe341: TiPipe;
    iPipe342: TiPipe;
    iValve122: TiValve;
    iPipe343: TiPipe;
    iValve123: TiValve;
    iPipe344: TiPipe;
    iPipe345: TiPipe;
    iPipe346: TiPipe;
    AdvPanel22: TAdvPanel;
    Label258: TLabel;
    Label259: TLabel;
    AdvPanel23: TAdvPanel;
    Label260: TLabel;
    Label261: TLabel;
    AdvPanel24: TAdvPanel;
    Label262: TLabel;
    Label263: TLabel;
    AdvPanel25: TAdvPanel;
    Label264: TLabel;
    Label265: TLabel;
    AdvPanel26: TAdvPanel;
    Label266: TLabel;
    Label267: TLabel;
    iPipe347: TiPipe;
    iValve124: TiValve;
    AdvPanel27: TAdvPanel;
    Label268: TLabel;
    Label269: TLabel;
    AdvPanel28: TAdvPanel;
    Label270: TLabel;
    Label271: TLabel;
    iPipe348: TiPipe;
    iPipe349: TiPipe;
    iPipe350: TiPipe;
    iPipe351: TiPipe;
    iPipe352: TiPipe;
    iPipe353: TiPipe;
    iPipe354: TiPipe;
    iLedArrow61: TiLedArrow;
    iPipe355: TiPipe;
    iPipe356: TiPipe;
    iPipe357: TiPipe;
    iValve125: TiValve;
    iValve126: TiValve;
    iPipe358: TiPipe;
    iValve127: TiValve;
    iPipe359: TiPipe;
    iValve128: TiValve;
    iPipe360: TiPipe;
    iPipe361: TiPipe;
    iPipe362: TiPipe;
    iPipe363: TiPipe;
    iPipe364: TiPipe;
    iPipe365: TiPipe;
    iPipe366: TiPipe;
    iPipe367: TiPipe;
    iPipe368: TiPipe;
    iPipe369: TiPipe;
    iValve129: TiValve;
    iPipe370: TiPipe;
    iLedArrow62: TiLedArrow;
    iPipe371: TiPipe;
    iValve130: TiValve;
    iPipe372: TiPipe;
    iPipe373: TiPipe;
    iPipe374: TiPipe;
    iValve131: TiValve;
    iPipe375: TiPipe;
    iPipe376: TiPipe;
    AdvPanel29: TAdvPanel;
    Label272: TLabel;
    Label273: TLabel;
    AdvPanel31: TAdvPanel;
    Label274: TLabel;
    Label275: TLabel;
    AdvPanel45: TAdvPanel;
    Label276: TLabel;
    Label277: TLabel;
    iPipe377: TiPipe;
    iValve132: TiValve;
    AdvPanel46: TAdvPanel;
    Label278: TLabel;
    Label279: TLabel;
    AdvPanel47: TAdvPanel;
    Label280: TLabel;
    Label281: TLabel;
    iPipe378: TiPipe;
    iPipe379: TiPipe;
    iPipe380: TiPipe;
    iPipe381: TiPipe;
    iValve133: TiValve;
    iPipe382: TiPipe;
    iPipe383: TiPipe;
    iValve134: TiValve;
    iPipe384: TiPipe;
    iPipe385: TiPipe;
    iPipe386: TiPipe;
    iValve135: TiValve;
    iValve136: TiValve;
    iValve137: TiValve;
    iPipe387: TiPipe;
    AdvPanel48: TAdvPanel;
    JvLabel103: TJvLabel;
    JvLabel104: TJvLabel;
    AdvPanel49: TAdvPanel;
    JvLabel105: TJvLabel;
    JvLabel106: TJvLabel;
    AdvPanel50: TAdvPanel;
    JvLabel107: TJvLabel;
    iPipe388: TiPipe;
    iPipe389: TiPipe;
    iPipe390: TiPipe;
    iPipe391: TiPipe;
    iPipe392: TiPipe;
    iPipe393: TiPipe;
    iPipe394: TiPipe;
    iPipe395: TiPipe;
    iPipe396: TiPipe;
    iPipe397: TiPipe;
    iValve138: TiValve;
    iValve139: TiValve;
    iPipe398: TiPipe;
    iValve140: TiValve;
    iPipe399: TiPipe;
    iValve141: TiValve;
    iPipe400: TiPipe;
    iPipe401: TiPipe;
    iPipe402: TiPipe;
    iPipe403: TiPipe;
    iPipe404: TiPipe;
    iPipe405: TiPipe;
    iPipe406: TiPipe;
    iPipe407: TiPipe;
    iPipe408: TiPipe;
    iPipe409: TiPipe;
    iPipe410: TiPipe;
    iPipe411: TiPipe;
    iPipe412: TiPipe;
    iPipe413: TiPipe;
    iPipe414: TiPipe;
    iPipe415: TiPipe;
    iPipe416: TiPipe;
    AdvPanel51: TAdvPanel;
    JvLabel108: TJvLabel;
    JvLabel109: TJvLabel;
    iValve142: TiValve;
    iPipe417: TiPipe;
    AdvPanel52: TAdvPanel;
    JvLabel110: TJvLabel;
    JvLabel331: TJvLabel;
    iValve143: TiValve;
    iPipe418: TiPipe;
    iPipe419: TiPipe;
    iPipe420: TiPipe;
    iPipe421: TiPipe;
    iPipe422: TiPipe;
    iPipe423: TiPipe;
    iPipe424: TiPipe;
    AdvPanel53: TAdvPanel;
    Label282: TLabel;
    Label283: TLabel;
    iValve144: TiValve;
    AdvPanel54: TAdvPanel;
    Label286: TLabel;
    Label287: TLabel;
    iPipe425: TiPipe;
    iPipe426: TiPipe;
    iPipe427: TiPipe;
    iPipe428: TiPipe;
    iPipe429: TiPipe;
    iPipe430: TiPipe;
    iValve145: TiValve;
    iPipe431: TiPipe;
    iValve146: TiValve;
    Panel4: TPanel;
    iPipe432: TiPipe;
    iPipe433: TiPipe;
    iPipe434: TiPipe;
    iPipe435: TiPipe;
    iPipeJoint1: TiPipeJoint;
    iPipeJoint29: TiPipeJoint;
    iPipe436: TiPipe;
    iPipe437: TiPipe;
    iPipe438: TiPipe;
    iPipe439: TiPipe;
    iPipe440: TiPipe;
    iPipe441: TiPipe;
    iPipe442: TiPipe;
    iPipe443: TiPipe;
    iPipe444: TiPipe;
    iPipe445: TiPipe;
    iPipe446: TiPipe;
    iPipe447: TiPipe;
    iPipeJoint30: TiPipeJoint;
    iPipe448: TiPipe;
    iValve147: TiValve;
    iPipe449: TiPipe;
    iPipe450: TiPipe;
    iPipe451: TiPipe;
    iValve149: TiValve;
    iPipe452: TiPipe;
    iPipe453: TiPipe;
    iPipe454: TiPipe;
    iPipeJoint31: TiPipeJoint;
    iPipeJoint32: TiPipeJoint;
    iPipe455: TiPipe;
    iPipe776: TiPipe;
    iPipe777: TiPipe;
    iPipeJoint33: TiPipeJoint;
    iPipeJoint34: TiPipeJoint;
    iPipeJoint35: TiPipeJoint;
    iPipeJoint87: TiPipeJoint;
    iPipeJoint88: TiPipeJoint;
    iPipeJoint89: TiPipeJoint;
    iPipeJoint90: TiPipeJoint;
    iPipeJoint91: TiPipeJoint;
    iPipeJoint92: TiPipeJoint;
    iPipeJoint93: TiPipeJoint;
    iPipeJoint94: TiPipeJoint;
    iPipeJoint95: TiPipeJoint;
    iLedArrow63: TiLedArrow;
    iPipe778: TiPipe;
    iPipeJoint96: TiPipeJoint;
    iPipeJoint97: TiPipeJoint;
    iPipe779: TiPipe;
    iValve234: TiValve;
    AdvTabSheet3: TAdvTabSheet;
    AdvScrollBox3: TAdvScrollBox;
    JvLabel24: TJvLabel;
    Shape12: TShape;
    Shape52: TShape;
    Shape77: TShape;
    Shape102: TShape;
    Shape103: TShape;
    Shape104: TShape;
    Shape105: TShape;
    Shape106: TShape;
    Shape108: TShape;
    Shape245: TShape;
    Shape246: TShape;
    Shape247: TShape;
    Shape248: TShape;
    Shape249: TShape;
    Image6: TImage;
    Image7: TImage;
    Label158: TLabel;
    Label159: TLabel;
    Label160: TLabel;
    Label161: TLabel;
    Label162: TLabel;
    Label163: TLabel;
    Label164: TLabel;
    Label165: TLabel;
    Label166: TLabel;
    Label167: TLabel;
    Label168: TLabel;
    Shape250: TShape;
    Shape251: TShape;
    Shape252: TShape;
    Shape253: TShape;
    Shape254: TShape;
    Shape255: TShape;
    Shape256: TShape;
    Shape257: TShape;
    Shape258: TShape;
    Shape259: TShape;
    Shape260: TShape;
    Shape261: TShape;
    Shape262: TShape;
    Label169: TLabel;
    JvLabel30: TJvLabel;
    JvLabel111: TJvLabel;
    Label170: TLabel;
    Shape263: TShape;
    Shape264: TShape;
    Label171: TLabel;
    Shape265: TShape;
    Shape266: TShape;
    Label172: TLabel;
    Shape267: TShape;
    Shape268: TShape;
    Shape269: TShape;
    Shape270: TShape;
    Shape271: TShape;
    Shape272: TShape;
    Label173: TLabel;
    Label174: TLabel;
    Shape273: TShape;
    Shape274: TShape;
    Label175: TLabel;
    Shape275: TShape;
    Shape276: TShape;
    Label176: TLabel;
    Label177: TLabel;
    Shape277: TShape;
    Shape278: TShape;
    Label178: TLabel;
    Shape279: TShape;
    Shape280: TShape;
    Label179: TLabel;
    Label180: TLabel;
    Shape281: TShape;
    Shape282: TShape;
    Shape283: TShape;
    Shape284: TShape;
    JvLabel112: TJvLabel;
    JvLabel113: TJvLabel;
    Shape285: TShape;
    JvLabel114: TJvLabel;
    JvLabel115: TJvLabel;
    JvLabel116: TJvLabel;
    JvLabel117: TJvLabel;
    Label181: TLabel;
    Label182: TLabel;
    Shape286: TShape;
    JvLabel118: TJvLabel;
    JvLabel119: TJvLabel;
    JvLabel120: TJvLabel;
    Label183: TLabel;
    Label184: TLabel;
    Shape287: TShape;
    JvLabel121: TJvLabel;
    Shape288: TShape;
    Shape289: TShape;
    Shape290: TShape;
    Label185: TLabel;
    Label186: TLabel;
    Shape291: TShape;
    Label187: TLabel;
    Label188: TLabel;
    Shape292: TShape;
    Shape293: TShape;
    Shape294: TShape;
    Label189: TLabel;
    Shape295: TShape;
    JvLabel122: TJvLabel;
    JvLabel123: TJvLabel;
    JvLabel124: TJvLabel;
    JvLabel125: TJvLabel;
    Shape296: TShape;
    Label190: TLabel;
    JvLabel126: TJvLabel;
    JvLabel127: TJvLabel;
    Shape297: TShape;
    JvLabel128: TJvLabel;
    JvLabel129: TJvLabel;
    JvLabel130: TJvLabel;
    JvLabel131: TJvLabel;
    JvLabel132: TJvLabel;
    Shape298: TShape;
    JvLabel133: TJvLabel;
    JvLabel134: TJvLabel;
    JvLabel135: TJvLabel;
    Shape299: TShape;
    Shape300: TShape;
    Shape301: TShape;
    Shape302: TShape;
    Shape303: TShape;
    Label191: TLabel;
    JvLabel136: TJvLabel;
    JvLabel137: TJvLabel;
    Label192: TLabel;
    Shape304: TShape;
    Shape305: TShape;
    Label193: TLabel;
    Shape306: TShape;
    Shape307: TShape;
    Label194: TLabel;
    Shape308: TShape;
    Shape309: TShape;
    Shape310: TShape;
    Shape311: TShape;
    Shape312: TShape;
    Shape313: TShape;
    Label195: TLabel;
    Label196: TLabel;
    Shape314: TShape;
    Shape315: TShape;
    Label197: TLabel;
    Shape316: TShape;
    Shape317: TShape;
    Label198: TLabel;
    Label199: TLabel;
    Shape318: TShape;
    Shape319: TShape;
    Label200: TLabel;
    Shape320: TShape;
    Shape321: TShape;
    Label201: TLabel;
    Label202: TLabel;
    Shape322: TShape;
    Shape323: TShape;
    Shape324: TShape;
    Shape325: TShape;
    Shape326: TShape;
    Shape327: TShape;
    Shape328: TShape;
    Shape329: TShape;
    Label203: TLabel;
    Shape330: TShape;
    Shape331: TShape;
    Label204: TLabel;
    Shape332: TShape;
    Label205: TLabel;
    Shape333: TShape;
    Shape334: TShape;
    Label206: TLabel;
    Shape335: TShape;
    Shape336: TShape;
    Label207: TLabel;
    Shape337: TShape;
    Label208: TLabel;
    JvLabel138: TJvLabel;
    JvLabel139: TJvLabel;
    JvLabel140: TJvLabel;
    Shape338: TShape;
    Shape339: TShape;
    Shape340: TShape;
    Label209: TLabel;
    JvLabel141: TJvLabel;
    JvLabel142: TJvLabel;
    Label210: TLabel;
    Shape341: TShape;
    Label211: TLabel;
    Shape342: TShape;
    Label212: TLabel;
    Shape343: TShape;
    Shape344: TShape;
    Shape345: TShape;
    Shape346: TShape;
    Shape347: TShape;
    Shape348: TShape;
    Label213: TLabel;
    Label214: TLabel;
    Shape349: TShape;
    Label215: TLabel;
    Shape350: TShape;
    Label216: TLabel;
    Label217: TLabel;
    Shape351: TShape;
    Shape352: TShape;
    Label218: TLabel;
    Shape353: TShape;
    Shape354: TShape;
    Label219: TLabel;
    Label220: TLabel;
    Shape355: TShape;
    Shape356: TShape;
    Shape357: TShape;
    Shape358: TShape;
    Shape359: TShape;
    Shape360: TShape;
    Shape361: TShape;
    Shape362: TShape;
    Label221: TLabel;
    JvLabel143: TJvLabel;
    JvLabel144: TJvLabel;
    Label222: TLabel;
    Shape363: TShape;
    Label223: TLabel;
    Shape364: TShape;
    Label224: TLabel;
    Shape365: TShape;
    Shape366: TShape;
    Shape367: TShape;
    Shape368: TShape;
    Shape369: TShape;
    Shape370: TShape;
    Label225: TLabel;
    Label226: TLabel;
    Shape371: TShape;
    Label227: TLabel;
    Shape372: TShape;
    Label228: TLabel;
    Shape522: TShape;
    Shape523: TShape;
    Shape524: TShape;
    Shape525: TShape;
    Shape526: TShape;
    Shape527: TShape;
    Shape528: TShape;
    Label229: TLabel;
    Shape529: TShape;
    Shape530: TShape;
    Label230: TLabel;
    Shape531: TShape;
    Label231: TLabel;
    Shape532: TShape;
    Shape533: TShape;
    Label232: TLabel;
    Shape534: TShape;
    Shape535: TShape;
    Label233: TLabel;
    Shape536: TShape;
    Label234: TLabel;
    Label235: TLabel;
    Label236: TLabel;
    Label237: TLabel;
    Shape537: TShape;
    Label238: TLabel;
    Shape538: TShape;
    JvLabel145: TJvLabel;
    JvLabel146: TJvLabel;
    JvLabel147: TJvLabel;
    JvLabel148: TJvLabel;
    JvLabel149: TJvLabel;
    JvLabel150: TJvLabel;
    Shape539: TShape;
    JvLabel151: TJvLabel;
    JvLabel152: TJvLabel;
    JvLabel153: TJvLabel;
    JvLabel154: TJvLabel;
    JvLabel155: TJvLabel;
    JvLabel156: TJvLabel;
    Shape540: TShape;
    Shape541: TShape;
    Shape542: TShape;
    Shape543: TShape;
    Shape544: TShape;
    JvLabel157: TJvLabel;
    JvLabel158: TJvLabel;
    Shape545: TShape;
    Label239: TLabel;
    Shape546: TShape;
    Label240: TLabel;
    Label241: TLabel;
    Shape547: TShape;
    Shape548: TShape;
    Label242: TLabel;
    Shape549: TShape;
    Shape550: TShape;
    Label243: TLabel;
    Label244: TLabel;
    Shape551: TShape;
    Shape552: TShape;
    Shape553: TShape;
    Shape554: TShape;
    Shape555: TShape;
    Shape556: TShape;
    JvLabel159: TJvLabel;
    JvLabel160: TJvLabel;
    JvLabel161: TJvLabel;
    JvLabel162: TJvLabel;
    JvLabel163: TJvLabel;
    JvLabel164: TJvLabel;
    JvLabel165: TJvLabel;
    Label245: TLabel;
    Label246: TLabel;
    JvLabel166: TJvLabel;
    JvLabel167: TJvLabel;
    JvLabel168: TJvLabel;
    JvLabel169: TJvLabel;
    JvLabel170: TJvLabel;
    JvLabel171: TJvLabel;
    JvLabel172: TJvLabel;
    JvLabel173: TJvLabel;
    JvLabel174: TJvLabel;
    Shape557: TShape;
    Shape558: TShape;
    Shape559: TShape;
    Label247: TLabel;
    Label248: TLabel;
    Shape560: TShape;
    Label249: TLabel;
    Shape561: TShape;
    Label250: TLabel;
    Shape614: TShape;
    Shape615: TShape;
    Shape616: TShape;
    Shape617: TShape;
    Shape618: TShape;
    Shape619: TShape;
    Label251: TLabel;
    Label252: TLabel;
    JvLabel175: TJvLabel;
    JvLabel176: TJvLabel;
    JvLabel177: TJvLabel;
    JvLabel178: TJvLabel;
    JvLabel179: TJvLabel;
    JvLabel180: TJvLabel;
    JvLabel181: TJvLabel;
    JvLabel198: TJvLabel;
    JvLabel199: TJvLabel;
    JvLabel200: TJvLabel;
    JvLabel201: TJvLabel;
    JvLabel202: TJvLabel;
    JvLabel203: TJvLabel;
    JvLabel204: TJvLabel;
    JvLabel205: TJvLabel;
    JvLabel206: TJvLabel;
    JvLabel207: TJvLabel;
    JvLabel208: TJvLabel;
    JvLabel209: TJvLabel;
    JvLabel210: TJvLabel;
    JvLabel211: TJvLabel;
    JvLabel212: TJvLabel;
    JvLabel315: TJvLabel;
    JvLabel316: TJvLabel;
    JvLabel317: TJvLabel;
    JvLabel318: TJvLabel;
    Shape620: TShape;
    Shape621: TShape;
    Shape622: TShape;
    Label253: TLabel;
    Shape623: TShape;
    Shape624: TShape;
    Label254: TLabel;
    Shape625: TShape;
    Label255: TLabel;
    JvLabel319: TJvLabel;
    JvLabel320: TJvLabel;
    JvLabel321: TJvLabel;
    JvLabel322: TJvLabel;
    JvLabel323: TJvLabel;
    JvLabel324: TJvLabel;
    JvLabel325: TJvLabel;
    JvLabel326: TJvLabel;
    JvLabel327: TJvLabel;
    iPipe456: TiPipe;
    iPipe457: TiPipe;
    iPipe458: TiPipe;
    iPipe459: TiPipe;
    iPipe460: TiPipe;
    iPipe461: TiPipe;
    iPipe462: TiPipe;
    iPipe463: TiPipe;
    iPipe464: TiPipe;
    iPipe465: TiPipe;
    iPipe466: TiPipe;
    iPipe467: TiPipe;
    iPipe468: TiPipe;
    iPipe469: TiPipe;
    iPipeJoint41: TiPipeJoint;
    iPipeJoint42: TiPipeJoint;
    iValve82: TiValve;
    iValve83: TiValve;
    iValve85: TiValve;
    iValve92: TiValve;
    iValve148: TiValve;
    iValve150: TiValve;
    iValve151: TiValve;
    iValve152: TiValve;
    iValve153: TiValve;
    iValve154: TiValve;
    iPipe470: TiPipe;
    iPipe471: TiPipe;
    iPipe472: TiPipe;
    iPipe473: TiPipe;
    iValve155: TiValve;
    iPipe474: TiPipe;
    iPipe475: TiPipe;
    iValve156: TiValve;
    iPipe476: TiPipe;
    iPipe477: TiPipe;
    iPipe478: TiPipe;
    iPipe479: TiPipe;
    iValve157: TiValve;
    iPipe480: TiPipe;
    iPipe481: TiPipe;
    iPipe482: TiPipe;
    iLedArrow64: TiLedArrow;
    iPipe483: TiPipe;
    iPipe484: TiPipe;
    iValve158: TiValve;
    iPipe485: TiPipe;
    iPipe486: TiPipe;
    iPipe487: TiPipe;
    iPipe488: TiPipe;
    iPipe489: TiPipe;
    iPipeJoint44: TiPipeJoint;
    iPipeJoint45: TiPipeJoint;
    iPipe490: TiPipe;
    iValve159: TiValve;
    iPipe491: TiPipe;
    iPipe492: TiPipe;
    iLedArrow65: TiLedArrow;
    iLedArrow66: TiLedArrow;
    iPipe493: TiPipe;
    iPipe494: TiPipe;
    iLedArrow67: TiLedArrow;
    iPipe495: TiPipe;
    iLedArrow68: TiLedArrow;
    iLedArrow69: TiLedArrow;
    iPipe496: TiPipe;
    iPipe497: TiPipe;
    iPipe498: TiPipe;
    iPipe499: TiPipe;
    iLedArrow70: TiLedArrow;
    iPipe503: TiPipe;
    iPipe504: TiPipe;
    iPipe505: TiPipe;
    iPipe506: TiPipe;
    iPipeJoint46: TiPipeJoint;
    iValve160: TiValve;
    iPipe507: TiPipe;
    iPipe508: TiPipe;
    iPipeJoint47: TiPipeJoint;
    iPipe509: TiPipe;
    iPipe510: TiPipe;
    iPipe511: TiPipe;
    iPipe512: TiPipe;
    iPipe513: TiPipe;
    iPipe514: TiPipe;
    iPipe515: TiPipe;
    iPipe516: TiPipe;
    iValve161: TiValve;
    iPipe517: TiPipe;
    iPipeJoint48: TiPipeJoint;
    iPipe518: TiPipe;
    iValve162: TiValve;
    iPipeJoint49: TiPipeJoint;
    iPipe519: TiPipe;
    iPipe520: TiPipe;
    iPipe521: TiPipe;
    iPipe522: TiPipe;
    iPipe523: TiPipe;
    iValve163: TiValve;
    iPipe524: TiPipe;
    iPipe525: TiPipe;
    iPipe526: TiPipe;
    iPipe527: TiPipe;
    iValve164: TiValve;
    iPipe528: TiPipe;
    iPipe529: TiPipe;
    iPipeJoint50: TiPipeJoint;
    iPipe530: TiPipe;
    iPipeJoint51: TiPipeJoint;
    iPipe531: TiPipe;
    iPipe532: TiPipe;
    iPipe533: TiPipe;
    iPipe534: TiPipe;
    iPipe535: TiPipe;
    iPipe536: TiPipe;
    iPipe537: TiPipe;
    iValve165: TiValve;
    iValve166: TiValve;
    iLedArrow71: TiLedArrow;
    iValve167: TiValve;
    iPipe538: TiPipe;
    iPipe539: TiPipe;
    iPipe540: TiPipe;
    iPipeJoint52: TiPipeJoint;
    iPipeJoint53: TiPipeJoint;
    iPipeJoint54: TiPipeJoint;
    iPipe541: TiPipe;
    iLedArrow72: TiLedArrow;
    iLedArrow73: TiLedArrow;
    iLedArrow74: TiLedArrow;
    iLedArrow75: TiLedArrow;
    iLedArrow76: TiLedArrow;
    iLedArrow77: TiLedArrow;
    iPipe542: TiPipe;
    iPipe543: TiPipe;
    iPipe544: TiPipe;
    iPipe545: TiPipe;
    iPipe546: TiPipe;
    iPipeJoint55: TiPipeJoint;
    iLedArrow78: TiLedArrow;
    iPipe547: TiPipe;
    iValve168: TiValve;
    AdvPanel12: TAdvPanel;
    iPipe548: TiPipe;
    iPipe549: TiPipe;
    iPipe550: TiPipe;
    iPipe551: TiPipe;
    iPipe552: TiPipe;
    iValve169: TiValve;
    iPipe553: TiPipe;
    iPipe554: TiPipe;
    iPipe555: TiPipe;
    iPipe556: TiPipe;
    iPipeJoint56: TiPipeJoint;
    iPipe557: TiPipe;
    AdvPanel18: TAdvPanel;
    JvLabel328: TJvLabel;
    JvLabel329: TJvLabel;
    AdvPanel19: TAdvPanel;
    JvLabel330: TJvLabel;
    JvLabel363: TJvLabel;
    iPipeJoint57: TiPipeJoint;
    iPipe558: TiPipe;
    iPipe559: TiPipe;
    iPipe560: TiPipe;
    iPipe561: TiPipe;
    iPipe562: TiPipe;
    iPipe563: TiPipe;
    iPipe564: TiPipe;
    AdvPanel20: TAdvPanel;
    JvLabel364: TJvLabel;
    JvLabel365: TJvLabel;
    AdvPanel21: TAdvPanel;
    JvLabel366: TJvLabel;
    JvLabel367: TJvLabel;
    iPipe565: TiPipe;
    iPipe566: TiPipe;
    iPipe567: TiPipe;
    AdvPanel30: TAdvPanel;
    JvLabel368: TJvLabel;
    JvLabel369: TJvLabel;
    iPipe568: TiPipe;
    iValve170: TiValve;
    iValve171: TiValve;
    AdvPanel32: TAdvPanel;
    JvLabel370: TJvLabel;
    JvLabel371: TJvLabel;
    iPipe569: TiPipe;
    AdvPanel33: TAdvPanel;
    JvLabel372: TJvLabel;
    JvLabel373: TJvLabel;
    iPipe570: TiPipe;
    iPipe571: TiPipe;
    iValve173: TiValve;
    iPipe572: TiPipe;
    iPipe573: TiPipe;
    iPipe574: TiPipe;
    iValve174: TiValve;
    iPipe575: TiPipe;
    iPipe576: TiPipe;
    iPipe577: TiPipe;
    AdvPanel34: TAdvPanel;
    JvLabel374: TJvLabel;
    iPipe578: TiPipe;
    iPipe579: TiPipe;
    iPipe580: TiPipe;
    iPipe581: TiPipe;
    iValve175: TiValve;
    iValve176: TiValve;
    iValve177: TiValve;
    iValve178: TiValve;
    iPipe582: TiPipe;
    iLedArrow79: TiLedArrow;
    iPipe583: TiPipe;
    iPipe584: TiPipe;
    iPipe585: TiPipe;
    iPipeJoint58: TiPipeJoint;
    iPipe586: TiPipe;
    iPipe587: TiPipe;
    iPipe588: TiPipe;
    iValve179: TiValve;
    iPipe589: TiPipe;
    iValve180: TiValve;
    iPipe590: TiPipe;
    iPipe591: TiPipe;
    iPipe592: TiPipe;
    iPipe593: TiPipe;
    iPipe594: TiPipe;
    iPipe595: TiPipe;
    iValve181: TiValve;
    iPipeJoint59: TiPipeJoint;
    iPipe596: TiPipe;
    iPipe597: TiPipe;
    iPipe598: TiPipe;
    iPipe599: TiPipe;
    iValve182: TiValve;
    iPipe603: TiPipe;
    iPipe604: TiPipe;
    iValve183: TiValve;
    iPipe605: TiPipe;
    iPipe606: TiPipe;
    iPipe607: TiPipe;
    iPipe608: TiPipe;
    iValve184: TiValve;
    iPipe609: TiPipe;
    iPipe610: TiPipe;
    iPipe611: TiPipe;
    iLedArrow80: TiLedArrow;
    iPipe612: TiPipe;
    iPipe613: TiPipe;
    iValve185: TiValve;
    iPipe614: TiPipe;
    iPipe615: TiPipe;
    iPipe616: TiPipe;
    iPipe617: TiPipe;
    iPipe618: TiPipe;
    iPipeJoint60: TiPipeJoint;
    iPipeJoint79: TiPipeJoint;
    iPipe619: TiPipe;
    iValve186: TiValve;
    iPipe620: TiPipe;
    iPipe621: TiPipe;
    iLedArrow81: TiLedArrow;
    iLedArrow82: TiLedArrow;
    iPipe622: TiPipe;
    iPipe623: TiPipe;
    iLedArrow83: TiLedArrow;
    iPipe624: TiPipe;
    iLedArrow84: TiLedArrow;
    iLedArrow85: TiLedArrow;
    iPipe625: TiPipe;
    iPipe626: TiPipe;
    iPipe627: TiPipe;
    iPipe628: TiPipe;
    iValve187: TiValve;
    iValve188: TiValve;
    iValve189: TiValve;
    iValve190: TiValve;
    iPipe629: TiPipe;
    iLedArrow86: TiLedArrow;
    iPipe630: TiPipe;
    iPipe631: TiPipe;
    iPipe632: TiPipe;
    iPipeJoint80: TiPipeJoint;
    iPipe633: TiPipe;
    iPipe634: TiPipe;
    iPipe635: TiPipe;
    iValve191: TiValve;
    iPipe636: TiPipe;
    iValve192: TiValve;
    iPipe637: TiPipe;
    iPipe638: TiPipe;
    iPipe639: TiPipe;
    iPipe640: TiPipe;
    iPipe641: TiPipe;
    iPipe642: TiPipe;
    iValve193: TiValve;
    iPipeJoint81: TiPipeJoint;
    iPipe643: TiPipe;
    iPipe644: TiPipe;
    iPipe645: TiPipe;
    iPipe646: TiPipe;
    iPipe647: TiPipe;
    iPipe648: TiPipe;
    iPipe649: TiPipe;
    iPipe650: TiPipe;
    iValve194: TiValve;
    iPipe651: TiPipe;
    iPipe652: TiPipe;
    iValve195: TiValve;
    iPipe653: TiPipe;
    iPipe654: TiPipe;
    iPipe655: TiPipe;
    iPipe656: TiPipe;
    iPipe657: TiPipe;
    iPipe658: TiPipe;
    iLedArrow87: TiLedArrow;
    iLedArrow88: TiLedArrow;
    iPipe659: TiPipe;
    iPipe660: TiPipe;
    iPipe661: TiPipe;
    iPipe662: TiPipe;
    iValve196: TiValve;
    iValve197: TiValve;
    AdvPanel35: TAdvPanel;
    iPipe663: TiPipe;
    iValve198: TiValve;
    AdvPanel36: TAdvPanel;
    iPipe664: TiPipe;
    iValve199: TiValve;
    AdvPanel37: TAdvPanel;
    iPipe665: TiPipe;
    iPipe666: TiPipe;
    iPipe667: TiPipe;
    iValve200: TiValve;
    iPipe668: TiPipe;
    iPipe669: TiPipe;
    iValve201: TiValve;
    AdvPanel38: TAdvPanel;
    iPipe670: TiPipe;
    iPipe671: TiPipe;
    iPipe672: TiPipe;
    iValve202: TiValve;
    iPipe673: TiPipe;
    iValve203: TiValve;
    iPipe674: TiPipe;
    iPipe675: TiPipe;
    iPipe676: TiPipe;
    iValve204: TiValve;
    iPipe677: TiPipe;
    iPipe678: TiPipe;
    iPipe679: TiPipe;
    iLedArrow89: TiLedArrow;
    iPipe680: TiPipe;
    iValve205: TiValve;
    iPipe681: TiPipe;
    iPipe682: TiPipe;
    iPipe683: TiPipe;
    iPipe684: TiPipe;
    iPipe685: TiPipe;
    iPipe686: TiPipe;
    iValve206: TiValve;
    iPipe687: TiPipe;
    iPipe688: TiPipe;
    iLedArrow90: TiLedArrow;
    iLedArrow91: TiLedArrow;
    iPipe689: TiPipe;
    iPipe690: TiPipe;
    iLedArrow92: TiLedArrow;
    iPipe691: TiPipe;
    iLedArrow93: TiLedArrow;
    iLedArrow94: TiLedArrow;
    iPipe692: TiPipe;
    iPipe693: TiPipe;
    iPipe694: TiPipe;
    iPipe695: TiPipe;
    iValve207: TiValve;
    iValve208: TiValve;
    iValve209: TiValve;
    iValve210: TiValve;
    iLedArrow95: TiLedArrow;
    iPipe696: TiPipe;
    iPipe697: TiPipe;
    iPipe698: TiPipe;
    iPipeJoint82: TiPipeJoint;
    iPipe699: TiPipe;
    iPipe700: TiPipe;
    iPipe701: TiPipe;
    iValve211: TiValve;
    iPipe702: TiPipe;
    iValve212: TiValve;
    iPipe703: TiPipe;
    iPipe704: TiPipe;
    iPipe705: TiPipe;
    iPipe706: TiPipe;
    iPipe707: TiPipe;
    iPipe708: TiPipe;
    iValve213: TiValve;
    iPipeJoint83: TiPipeJoint;
    iPipe709: TiPipe;
    iPipe710: TiPipe;
    iPipe711: TiPipe;
    iPipe712: TiPipe;
    iValve214: TiValve;
    iPipe713: TiPipe;
    iPipe714: TiPipe;
    iValve215: TiValve;
    iPipe715: TiPipe;
    iPipe716: TiPipe;
    iPipe717: TiPipe;
    iPipe718: TiPipe;
    iValve216: TiValve;
    iPipe719: TiPipe;
    iPipe720: TiPipe;
    iPipe721: TiPipe;
    iLedArrow96: TiLedArrow;
    iPipe722: TiPipe;
    iPipe723: TiPipe;
    iValve217: TiValve;
    iPipe724: TiPipe;
    iPipe725: TiPipe;
    iPipe726: TiPipe;
    iPipeJoint84: TiPipeJoint;
    iPipeJoint85: TiPipeJoint;
    iPipe727: TiPipe;
    iValve218: TiValve;
    iPipe728: TiPipe;
    iPipe729: TiPipe;
    iLedArrow97: TiLedArrow;
    iLedArrow98: TiLedArrow;
    iPipe730: TiPipe;
    iPipe731: TiPipe;
    iLedArrow99: TiLedArrow;
    iPipe732: TiPipe;
    iLedArrow101: TiLedArrow;
    iLedArrow142: TiLedArrow;
    iPipe733: TiPipe;
    iValve219: TiValve;
    iValve220: TiValve;
    iLedArrow143: TiLedArrow;
    iPipe734: TiPipe;
    iPipe735: TiPipe;
    iPipe736: TiPipe;
    iPipeJoint86: TiPipeJoint;
    iPipe737: TiPipe;
    iPipe738: TiPipe;
    iPipe739: TiPipe;
    iValve221: TiValve;
    iPipe740: TiPipe;
    iValve222: TiValve;
    iPipe741: TiPipe;
    iPipe742: TiPipe;
    iPipe743: TiPipe;
    iPipe744: TiPipe;
    iPipe745: TiPipe;
    iPipe746: TiPipe;
    iValve223: TiValve;
    iPipeJoint113: TiPipeJoint;
    iPipe747: TiPipe;
    iPipe748: TiPipe;
    iPipe749: TiPipe;
    iPipe750: TiPipe;
    iPipe751: TiPipe;
    iPipe752: TiPipe;
    iPipe753: TiPipe;
    iPipe754: TiPipe;
    iValve224: TiValve;
    iPipe755: TiPipe;
    iPipe756: TiPipe;
    iValve225: TiValve;
    iPipe757: TiPipe;
    iPipe758: TiPipe;
    iPipe759: TiPipe;
    iPipe760: TiPipe;
    iValve226: TiValve;
    AdvPanel39: TAdvPanel;
    iPipe761: TiPipe;
    iPipe762: TiPipe;
    iPipe763: TiPipe;
    iPipe764: TiPipe;
    iPipe765: TiPipe;
    iValve227: TiValve;
    iPipe766: TiPipe;
    iPipeJoint119: TiPipeJoint;
    iPipe767: TiPipe;
    iPipe768: TiPipe;
    iPipe769: TiPipe;
    iValve228: TiValve;
    iValve229: TiValve;
    iPipe770: TiPipe;
    iValve230: TiValve;
    iPipe771: TiPipe;
    iPipe773: TiPipe;
    iPipe775: TiPipe;
    iValve231: TiValve;
    iPipe1128: TiPipe;
    iPipe1129: TiPipe;
    iPipe1130: TiPipe;
    iPipe1131: TiPipe;
    iPipe1132: TiPipe;
    AdvPanel40: TAdvPanel;
    JvLabel375: TJvLabel;
    iPipe1133: TiPipe;
    iPipe1134: TiPipe;
    AdvPanel41: TAdvPanel;
    iPipe1135: TiPipe;
    AdvPanel42: TAdvPanel;
    JvLabel376: TJvLabel;
    iValve232: TiValve;
    iValve328: TiValve;
    iPipe1136: TiPipe;
    iValve329: TiValve;
    iPipe1137: TiPipe;
    iPipe1138: TiPipe;
    iPipe1139: TiPipe;
    iPipe1140: TiPipe;
    iValve330: TiValve;
    iPipe1141: TiPipe;
    iPipe1142: TiPipe;
    iPipe1143: TiPipe;
    iLedArrow144: TiLedArrow;
    iPipe1144: TiPipe;
    iValve331: TiValve;
    iPipe1145: TiPipe;
    iPipe1146: TiPipe;
    iPipe1147: TiPipe;
    iPipe1148: TiPipe;
    iPipe1149: TiPipe;
    iLedArrow145: TiLedArrow;
    iLedArrow146: TiLedArrow;
    iPipe1150: TiPipe;
    iPipe1151: TiPipe;
    iPipe1152: TiPipe;
    iPipe1219: TiPipe;
    iValve332: TiValve;
    iValve333: TiValve;
    iValve334: TiValve;
    iValve335: TiValve;
    iLedArrow156: TiLedArrow;
    iPipe1220: TiPipe;
    iPipeJoint120: TiPipeJoint;
    iValve336: TiValve;
    iPipe1221: TiPipe;
    iPipe1222: TiPipe;
    iPipe1223: TiPipe;
    iPipe1224: TiPipe;
    iPipe1225: TiPipe;
    iValve337: TiValve;
    iPipeJoint121: TiPipeJoint;
    iPipe1226: TiPipe;
    iPipe1227: TiPipe;
    iPipe1228: TiPipe;
    iValve338: TiValve;
    AdvPanel43: TAdvPanel;
    iPipe1229: TiPipe;
    iValve339: TiValve;
    iPipe1230: TiPipe;
    iPipe1231: TiPipe;
    iValve361: TiValve;
    iValve362: TiValve;
    iPipeJoint122: TiPipeJoint;
    iPipeJoint123: TiPipeJoint;
    iPipeJoint124: TiPipeJoint;
    iPipeJoint125: TiPipeJoint;
    iPipeJoint126: TiPipeJoint;
    iPipeJoint127: TiPipeJoint;
    iPipe1232: TiPipe;
    iPipe1233: TiPipe;
    iPipe1234: TiPipe;
    iPipe1235: TiPipe;
    iPipe1236: TiPipe;
    iPipe1237: TiPipe;
    iPipe1238: TiPipe;
    iValve363: TiValve;
    iPipe1239: TiPipe;
    iPipe1240: TiPipe;
    iValve364: TiValve;
    iPipe1241: TiPipe;
    iPipe1242: TiPipe;
    iPipe1243: TiPipe;
    iValve365: TiValve;
    iPipe1244: TiPipe;
    iPipe1245: TiPipe;
    iPipe1246: TiPipe;
    iPipe1247: TiPipe;
    iLedArrow157: TiLedArrow;
    iPipe1248: TiPipe;
    iLedArrow158: TiLedArrow;
    iLedArrow159: TiLedArrow;
    iPipe1249: TiPipe;
    iPipe1250: TiPipe;
    iPipe1251: TiPipe;
    iPipe1252: TiPipe;
    iValve366: TiValve;
    iPipe1253: TiPipe;
    iPipe1254: TiPipe;
    iPipe1255: TiPipe;
    iPipeJoint128: TiPipeJoint;
    AdvPanel44: TAdvPanel;
    JvLabel377: TJvLabel;
    iPipe1256: TiPipe;
    iPipe1257: TiPipe;
    iValve367: TiValve;
    Button23: TButton;
    Button24: TButton;
    Button25: TButton;
    Button26: TButton;
    Button27: TButton;
    Button28: TButton;
    Button29: TButton;
    iPipe1258: TiPipe;
    iPipe1259: TiPipe;
    iPipeJoint129: TiPipeJoint;
    iPipe1260: TiPipe;
    iPipe1261: TiPipe;
    Button30: TButton;
    iPipe1262: TiPipe;
    iPipe1263: TiPipe;
    iValve368: TiValve;
    iPipe1264: TiPipe;
    iValve369: TiValve;
    AdvTabSheet5: TAdvTabSheet;
    AdvScrollBox4: TAdvScrollBox;
    Image3: TImage;
    iPipe782: TiPipe;
    iPipe784: TiPipe;
    iPipe785: TiPipe;
    iPipe788: TiPipe;
    iPipe791: TiPipe;
    iPipe796: TiPipe;
    iPipe815: TiPipe;
    iPipe820: TiPipe;
    iPipe821: TiPipe;
    iPipe822: TiPipe;
    iValve245: TiValve;
    iValve247: TiValve;
    JvLabel229: TJvLabel;
    JvLabel231: TJvLabel;
    JvLabel232: TJvLabel;
    Label295: TLabel;
    Label296: TLabel;
    Label300: TLabel;
    Label301: TLabel;
    Label303: TLabel;
    Shape374: TShape;
    Shape380: TShape;
    Shape385: TShape;
    Shape386: TShape;
    Shape387: TShape;
    Shape388: TShape;
    Shape389: TShape;
    Shape390: TShape;
    Shape391: TShape;
    Shape392: TShape;
    iPipe780: TiPipe;
    JvLabel219: TJvLabel;
    iLedArrow102: TiLedArrow;
    iPipe781: TiPipe;
    iPipe786: TiPipe;
    iPipe787: TiPipe;
    iPipeJoint3: TiPipeJoint;
    JvLabel220: TJvLabel;
    iValve76: TiValve;
    iPipeJoint4: TiPipeJoint;
    iValve172: TiValve;
    JvLabel221: TJvLabel;
    Label292: TLabel;
    Shape110: TShape;
    Shape373: TShape;
    Shape375: TShape;
    Label293: TLabel;
    JvLabel222: TJvLabel;
    JvLabel223: TJvLabel;
    Shape377: TShape;
    Label298: TLabel;
    Shape381: TShape;
    Shape382: TShape;
    Shape383: TShape;
    Shape393: TShape;
    Shape394: TShape;
    Label302: TLabel;
    Label304: TLabel;
    JvLabel226: TJvLabel;
    iPipe789: TiPipe;
    iPipe790: TiPipe;
    iPipe793: TiPipe;
    iValve233: TiValve;
    iValve235: TiValve;
    iPipe797: TiPipe;
    iPipe798: TiPipe;
    iPipe805: TiPipe;
    iPipe806: TiPipe;
    iPipe814: TiPipe;
    iPipeJoint2: TiPipeJoint;
    iPipeJoint5: TiPipeJoint;
    iPipe818: TiPipe;
    iPipe823: TiPipe;
    iPipeJoint61: TiPipeJoint;
    iPipe824: TiPipe;
    iPipe825: TiPipe;
    iPipe826: TiPipe;
    iLedArrow107: TiLedArrow;
    iLedArrow108: TiLedArrow;
    Panel7: TPanel;
    iValve237: TiValve;
    iLedArrow109: TiLedArrow;
    iLedArrow100: TiLedArrow;
    iLedArrow110: TiLedArrow;
    Shape395: TShape;
    iPipe783: TiPipe;
    iPipe799: TiPipe;
    iPipe801: TiPipe;
    iPipe807: TiPipe;
    iLedArrow106: TiLedArrow;
    JvLabel225: TJvLabel;
    JvLabel227: TJvLabel;
    Shape376: TShape;
    Label294: TLabel;
    iPipe792: TiPipe;
    iValve238: TiValve;
    JvLabel230: TJvLabel;
    iPipe808: TiPipe;
    iPipe809: TiPipe;
    iPipe811: TiPipe;
    iValve240: TiValve;
    Label297: TLabel;
    JvLabel233: TJvLabel;
    JvLabel234: TJvLabel;
    iPipeJoint62: TiPipeJoint;
    iValve239: TiValve;
    iValve241: TiValve;
    iValve242: TiValve;
    Shape384: TShape;
    iPipe810: TiPipe;
    iValve244: TiValve;
    iPipe812: TiPipe;
    iPipe813: TiPipe;
    iPipe816: TiPipe;
    iPipe794: TiPipe;
    iPipe795: TiPipe;
    Shape378: TShape;
    Shape379: TShape;
    iPipe802: TiPipe;
    iPipe817: TiPipe;
    iPipe819: TiPipe;
    iValve236: TiValve;
    iPipe827: TiPipe;
    iValve243: TiValve;
    Label299: TLabel;
    Shape397: TShape;
    iValve246: TiValve;
    JvLabel224: TJvLabel;
    JvLabel235: TJvLabel;
    JvLabel236: TJvLabel;
    iPipe828: TiPipe;
    iValve248: TiValve;
    JvLabel238: TJvLabel;
    JvLabel239: TJvLabel;
    JvLabel240: TJvLabel;
    iPipe829: TiPipe;
    iPipe830: TiPipe;
    iPipe831: TiPipe;
    AdvPanel2: TAdvPanel;
    JvLabel237: TJvLabel;
    JvLabel241: TJvLabel;
    JvLabel242: TJvLabel;
    iPipe832: TiPipe;
    iPipe833: TiPipe;
    iPipe834: TiPipe;
    iValve249: TiValve;
    iPipe835: TiPipe;
    iValve250: TiValve;
    Label305: TLabel;
    Shape396: TShape;
    iValve251: TiValve;
    JvLabel243: TJvLabel;
    JvLabel244: TJvLabel;
    JvLabel245: TJvLabel;
    iPipe836: TiPipe;
    iValve252: TiValve;
    JvLabel246: TJvLabel;
    JvLabel247: TJvLabel;
    JvLabel248: TJvLabel;
    iPipe837: TiPipe;
    iPipe838: TiPipe;
    iPipe839: TiPipe;
    AdvPanel3: TAdvPanel;
    JvLabel249: TJvLabel;
    JvLabel250: TJvLabel;
    iPipe840: TiPipe;
    iPipe841: TiPipe;
    iPipe842: TiPipe;
    iValve253: TiValve;
    iPipe843: TiPipe;
    iValve254: TiValve;
    Label306: TLabel;
    Shape399: TShape;
    iValve255: TiValve;
    JvLabel251: TJvLabel;
    JvLabel252: TJvLabel;
    JvLabel253: TJvLabel;
    iPipe844: TiPipe;
    iValve256: TiValve;
    JvLabel254: TJvLabel;
    JvLabel255: TJvLabel;
    JvLabel256: TJvLabel;
    iPipe845: TiPipe;
    iPipe846: TiPipe;
    iPipe847: TiPipe;
    AdvPanel55: TAdvPanel;
    JvLabel257: TJvLabel;
    JvLabel258: TJvLabel;
    iLedArrow103: TiLedArrow;
    iPipe848: TiPipe;
    iPipe849: TiPipe;
    iPipe850: TiPipe;
    iValve257: TiValve;
    iPipe851: TiPipe;
    iValve258: TiValve;
    Label307: TLabel;
    Shape398: TShape;
    iValve259: TiValve;
    JvLabel259: TJvLabel;
    JvLabel260: TJvLabel;
    JvLabel261: TJvLabel;
    iPipe852: TiPipe;
    iValve260: TiValve;
    JvLabel262: TJvLabel;
    JvLabel263: TJvLabel;
    JvLabel264: TJvLabel;
    iPipe853: TiPipe;
    iPipe854: TiPipe;
    iPipe855: TiPipe;
    AdvPanel56: TAdvPanel;
    JvLabel265: TJvLabel;
    JvLabel266: TJvLabel;
    iPipe856: TiPipe;
    iPipe857: TiPipe;
    iPipe858: TiPipe;
    iValve261: TiValve;
    iPipe859: TiPipe;
    iValve262: TiValve;
    Label308: TLabel;
    Shape400: TShape;
    iValve263: TiValve;
    JvLabel267: TJvLabel;
    JvLabel268: TJvLabel;
    JvLabel269: TJvLabel;
    iPipe860: TiPipe;
    iValve264: TiValve;
    JvLabel270: TJvLabel;
    JvLabel271: TJvLabel;
    JvLabel272: TJvLabel;
    iPipe861: TiPipe;
    iPipe862: TiPipe;
    iPipe863: TiPipe;
    AdvPanel57: TAdvPanel;
    JvLabel273: TJvLabel;
    JvLabel274: TJvLabel;
    iPipe864: TiPipe;
    iPipe865: TiPipe;
    iPipe866: TiPipe;
    iValve265: TiValve;
    iPipe867: TiPipe;
    iValve266: TiValve;
    Label309: TLabel;
    Shape401: TShape;
    iValve267: TiValve;
    JvLabel275: TJvLabel;
    JvLabel276: TJvLabel;
    JvLabel277: TJvLabel;
    iPipe868: TiPipe;
    iValve268: TiValve;
    JvLabel278: TJvLabel;
    JvLabel279: TJvLabel;
    JvLabel280: TJvLabel;
    iPipe869: TiPipe;
    iPipe870: TiPipe;
    iPipe871: TiPipe;
    AdvPanel58: TAdvPanel;
    JvLabel281: TJvLabel;
    JvLabel282: TJvLabel;
    Label310: TLabel;
    JvLabel283: TJvLabel;
    Shape402: TShape;
    iPipe872: TiPipe;
    iPipe873: TiPipe;
    JvLabel284: TJvLabel;
    Shape403: TShape;
    iPipe874: TiPipe;
    iPipe875: TiPipe;
    iPipe876: TiPipe;
    iPipe877: TiPipe;
    AdvTabSheet4: TAdvTabSheet;
    AdvScrollBox5: TAdvScrollBox;
    JvLabel288: TJvLabel;
    Label315: TLabel;
    Shape419: TShape;
    JvLabel292: TJvLabel;
    Label328: TLabel;
    iPipe879: TiPipe;
    iPipe880: TiPipe;
    iPipe881: TiPipe;
    iPipe886: TiPipe;
    iPipe887: TiPipe;
    iPipe893: TiPipe;
    Shape410: TShape;
    Label312: TLabel;
    Shape404: TShape;
    Shape406: TShape;
    JvLabel286: TJvLabel;
    iPipe878: TiPipe;
    Label316: TLabel;
    iPipe882: TiPipe;
    iPipe883: TiPipe;
    iPipe884: TiPipe;
    iPipe885: TiPipe;
    iPipe888: TiPipe;
    iValve270: TiValve;
    iLedArrow104: TiLedArrow;
    iValve271: TiValve;
    Shape405: TShape;
    JvLabel287: TJvLabel;
    Shape426: TShape;
    Label325: TLabel;
    Shape427: TShape;
    Shape428: TShape;
    Label326: TLabel;
    Shape429: TShape;
    Shape430: TShape;
    Label327: TLabel;
    Label329: TLabel;
    Shape431: TShape;
    Shape432: TShape;
    JvLabel291: TJvLabel;
    iPipe889: TiPipe;
    iPipe890: TiPipe;
    iPipe910: TiPipe;
    iPipe911: TiPipe;
    iPipe912: TiPipe;
    iValve276: TiValve;
    iPipe913: TiPipe;
    iPipe914: TiPipe;
    iValve277: TiValve;
    iPipeJoint43: TiPipeJoint;
    iPipeJoint63: TiPipeJoint;
    iPipe915: TiPipe;
    iPipe891: TiPipe;
    iPipe907: TiPipe;
    iPipe908: TiPipe;
    iPipe909: TiPipe;
    iPipe921: TiPipe;
    iPipe922: TiPipe;
    iPipe923: TiPipe;
    iValve279: TiValve;
    Shape435: TShape;
    Label330: TLabel;
    Shape436: TShape;
    Label331: TLabel;
    JvLabel289: TJvLabel;
    JvLabel290: TJvLabel;
    Shape437: TShape;
    Shape438: TShape;
    Label332: TLabel;
    JvLabel293: TJvLabel;
    Shape439: TShape;
    iPipe924: TiPipe;
    iValve281: TiValve;
    Label335: TLabel;
    AdvPanel61: TAdvPanel;
    iPipe926: TiPipe;
    iValve280: TiValve;
    AdvPanel60: TAdvPanel;
    Label334: TLabel;
    Label333: TLabel;
    iPipe925: TiPipe;
    iValve282: TiValve;
    AdvPanel62: TAdvPanel;
    Label336: TLabel;
    iPipe927: TiPipe;
    iPipe928: TiPipe;
    JvLabel294: TJvLabel;
    JvLabel295: TJvLabel;
    iPipe929: TiPipe;
    iValve283: TiValve;
    iPipe930: TiPipe;
    iValve284: TiValve;
    Shape440: TShape;
    JvLabel296: TJvLabel;
    Label337: TLabel;
    iValve285: TiValve;
    iPipe931: TiPipe;
    Shape442: TShape;
    Shape445: TShape;
    Label339: TLabel;
    Shape446: TShape;
    JvLabel297: TJvLabel;
    JvLabel298: TJvLabel;
    Shape452: TShape;
    Label342: TLabel;
    JvLabel299: TJvLabel;
    iPipe932: TiPipe;
    iValve287: TiValve;
    iPipe938: TiPipe;
    iPipe939: TiPipe;
    iPipe940: TiPipe;
    iLedArrow118: TiLedArrow;
    iLedArrow119: TiLedArrow;
    iLedArrow120: TiLedArrow;
    iPipe945: TiPipe;
    iValve288: TiValve;
    iPipe899: TiPipe;
    iPipe902: TiPipe;
    iPipe903: TiPipe;
    JvLabel285: TJvLabel;
    JvLabel300: TJvLabel;
    JvLabel301: TJvLabel;
    Shape412: TShape;
    Label318: TLabel;
    Shape413: TShape;
    Shape414: TShape;
    Label319: TLabel;
    Shape415: TShape;
    Shape416: TShape;
    Label320: TLabel;
    Label321: TLabel;
    Shape417: TShape;
    Shape418: TShape;
    iPipe892: TiPipe;
    iPipe894: TiPipe;
    iPipe895: TiPipe;
    iValve269: TiValve;
    iPipe896: TiPipe;
    iPipe897: TiPipe;
    iValve272: TiValve;
    iPipe898: TiPipe;
    iPipe901: TiPipe;
    iPipe904: TiPipe;
    iPipe905: TiPipe;
    Shape420: TShape;
    Shape421: TShape;
    Label322: TLabel;
    Shape422: TShape;
    JvLabel302: TJvLabel;
    JvLabel303: TJvLabel;
    Shape423: TShape;
    Label323: TLabel;
    JvLabel304: TJvLabel;
    iPipe906: TiPipe;
    iValve273: TiValve;
    iPipe916: TiPipe;
    iPipe917: TiPipe;
    iPipe918: TiPipe;
    iLedArrow105: TiLedArrow;
    iLedArrow113: TiLedArrow;
    iLedArrow114: TiLedArrow;
    iPipe919: TiPipe;
    iValve274: TiValve;
    iPipe920: TiPipe;
    iPipe941: TiPipe;
    iPipe942: TiPipe;
    JvLabel305: TJvLabel;
    JvLabel306: TJvLabel;
    iPipeJoint65: TiPipeJoint;
    iPipe950: TiPipe;
    iPipe951: TiPipe;
    iPipe933: TiPipe;
    iPipe934: TiPipe;
    iValve275: TiValve;
    JvLabel228: TJvLabel;
    iPipe935: TiPipe;
    Shape407: TShape;
    Label311: TLabel;
    Label317: TLabel;
    iValve278: TiValve;
    Label324: TLabel;
    AdvPanel63: TAdvPanel;
    iPipe936: TiPipe;
    iValve289: TiValve;
    iPipe937: TiPipe;
    Shape408: TShape;
    Label338: TLabel;
    Label340: TLabel;
    iPipe943: TiPipe;
    iValve286: TiValve;
    iPipe944: TiPipe;
    Shape409: TShape;
    Label341: TLabel;
    Label343: TLabel;
    iPipe946: TiPipe;
    iValve290: TiValve;
    iPipe947: TiPipe;
    Shape411: TShape;
    Label344: TLabel;
    Label345: TLabel;
    iPipe948: TiPipe;
    iValve291: TiValve;
    iPipe949: TiPipe;
    Shape424: TShape;
    Label346: TLabel;
    Label347: TLabel;
    iPipe952: TiPipe;
    iValve292: TiValve;
    iPipe953: TiPipe;
    iLedArrow121: TiLedArrow;
    Shape425: TShape;
    Label348: TLabel;
    Label349: TLabel;
    iPipe954: TiPipe;
    iValve293: TiValve;
    iLedArrow111: TiLedArrow;
    iLedArrow112: TiLedArrow;
    iLedArrow115: TiLedArrow;
    iLedArrow116: TiLedArrow;
    iLedArrow117: TiLedArrow;
    iPipe955: TiPipe;
    iPipe956: TiPipe;
    JvLabel307: TJvLabel;
    iPipe957: TiPipe;
    iValve294: TiValve;
    AdvPanel59: TAdvPanel;
    Button80: TButton;
    Button90: TButton;
    Button100: TButton;
    Button110: TButton;
    Button130: TButton;
    Button14: TButton;
    Button150: TButton;
    procedure Button1Click(Sender: TObject);
    procedure Button7Click(Sender: TObject);
    procedure Button3Click(Sender: TObject);
    procedure Button4Click(Sender: TObject);
    procedure Button6Click(Sender: TObject);
    procedure Button80Click(Sender: TObject);
    procedure Button100Click(Sender: TObject);
    procedure Button110Click(Sender: TObject);
    procedure Button130Click(Sender: TObject);
    procedure Button90Click(Sender: TObject);
    procedure Button150Click(Sender: TObject);
    procedure Button23Click(Sender: TObject);
    procedure Button24Click(Sender: TObject);
    procedure Button25Click(Sender: TObject);
    procedure Button26Click(Sender: TObject);
    procedure Button27Click(Sender: TObject);
    procedure Button28Click(Sender: TObject);
    procedure Button30Click(Sender: TObject);
  private
    { Private declarations }

  public
    { Public declarations }
  end;

var
  Pipe_Frm: TPipe_Frm;

implementation
uses
  CommonUtil_Unit;


{$R *.dfm}

{ TPipe_Frm }

procedure TPipe_Frm.Button100Click(Sender: TObject);
var
  i : integer;
begin
  for i := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TiPipe then
    begin
      if TiPipe(Self.Components[i]).Hint = 'LO1' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'LO3' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'LO2' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'U2' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'U2_' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
    end;
  end;
end;

procedure TPipe_Frm.Button110Click(Sender: TObject);
var
  i : integer;
begin
  for i := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TiPipe then
    begin
      if TiPipe(Self.Components[i]).Hint = 'LO1' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'LO3' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'LO2' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'U3' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'U3_' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
    end;
  end;
end;

procedure TPipe_Frm.Button130Click(Sender: TObject);
var
  i : integer;
begin
  for i := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TiPipe then
    begin
      if TiPipe(Self.Components[i]).Hint = 'LO1' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'LO2' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'U4' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'U4_' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
    end;
  end;
end;

procedure TPipe_Frm.Button150Click(Sender: TObject);
var
  i : integer;
begin
  for i := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TiPipe then
    begin
      if TiPipe(Self.Components[i]).Hint = 'LO1' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'LO2' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'U6' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'U6_' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
    end;
  end;
end;

procedure TPipe_Frm.Button1Click(Sender: TObject);
var
  i : integer;
begin
  for i := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TiPipe then
    begin
      if TiPipe(Self.Components[i]).Hint = '1000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '2000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '100' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '600' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '700' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := true ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
    end;
  end;
end;

procedure TPipe_Frm.Button23Click(Sender: TObject);
var
  i : integer;
begin
  for i := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TiPipe then
    begin
      if TiPipe(Self.Components[i]).Hint = '3000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '4000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '6000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '5000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '10' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
    end;
  end;
end;

procedure TPipe_Frm.Button24Click(Sender: TObject);
var
  i : integer;
begin
  for i := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TiPipe then
    begin
      if TiPipe(Self.Components[i]).Hint = '3000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '4000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '9000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '91' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '92' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '40' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
    end;
  end;
end;

procedure TPipe_Frm.Button25Click(Sender: TObject);
var
  i : integer;
begin
  for i := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TiPipe then
    begin
      if TiPipe(Self.Components[i]).Hint = '3000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '4000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '6000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '5000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '20' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
    end;
  end;
end;

procedure TPipe_Frm.Button26Click(Sender: TObject);
var
  i : integer;
begin
  for i := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TiPipe then
    begin
      if TiPipe(Self.Components[i]).Hint = '3000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '4000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '6000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '5000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '30' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
    end;
  end;
end;

procedure TPipe_Frm.Button27Click(Sender: TObject);
var
  i : integer;
begin
  for i := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TiPipe then
    begin
      if TiPipe(Self.Components[i]).Hint = '3000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '4000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '9000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '93' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '94' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
    end;
  end;
end;

procedure TPipe_Frm.Button28Click(Sender: TObject);
var
  i : integer;
begin
  for i := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TiPipe then
    begin
      if TiPipe(Self.Components[i]).Hint = '3000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '4000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '8000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '7000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '60' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
    end;
  end;
end;

procedure TPipe_Frm.Button30Click(Sender: TObject);
var
  i : integer;
begin
  for i := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TiPipe then
    begin
      if TiPipe(Self.Components[i]).Hint = '3000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '4000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '9000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '95' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '96' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '50' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
    end;
  end;
end;

procedure TPipe_Frm.Button3Click(Sender: TObject);
var
  i : integer;
begin
  for i := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TiPipe then
    begin
      if TiPipe(Self.Components[i]).Hint = '1000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '2000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '200' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '600' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '700' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := true ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
    end;
  end;
end;

procedure TPipe_Frm.Button4Click(Sender: TObject);
var
  i : integer;
begin
  for i := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TiPipe then
    begin
      if TiPipe(Self.Components[i]).Hint = '1000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '2000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '300' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '600' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '700' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := true ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
    end;
  end;
end;

procedure TPipe_Frm.Button6Click(Sender: TObject);
var
  i : integer;
begin
  for i := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TiPipe then
    begin
      if TiPipe(Self.Components[i]).Hint = '1000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '2000' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '400' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = '500' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
    end;
  end;
end;

procedure TPipe_Frm.Button7Click(Sender: TObject);
var
  i : integer;
begin
  for i := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TiPipe then
    begin
      TiPipe(Self.Components[i]).FlowOn := False ;
      TiPipe(Self.Components[i]).FlowReverse := False ;
      TiPipe(Self.Components[i]).TubeColor := clBlack ;
    end;
  end;
end;

procedure TPipe_Frm.Button80Click(Sender: TObject);
var
  i : integer;
begin
  for i := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TiPipe then
    begin
      if TiPipe(Self.Components[i]).Hint = 'LO1' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'LO3' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'LO2' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'U1' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'U1_' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
    end;
  end;
end;
procedure TPipe_Frm.Button90Click(Sender: TObject);
var
  i : integer;
begin
  for i := 0 to Self.ComponentCount-1 do
  begin
    if Self.Components[i] is TiPipe then
    begin
      if TiPipe(Self.Components[i]).Hint = 'LO1' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'LO3' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'LO2' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'U5' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := True ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
      if TiPipe(Self.Components[i]).Hint = 'U5_' then
      begin
        TiPipe(Self.Components[i]).FlowOn := True ;
        TiPipe(Self.Components[i]).FlowReverse := False ;
        TiPipe(Self.Components[i]).TubeColor := clMaroon ;
      end;
    end;
  end;
end;

end.
