unit IPCThrdConst_ECS_AVAT;

interface

const
  MAX_CLIENTS        = 6;
  TIMEOUT            = 2000;
  BUFFER_NAME        = 'BUFFER_NAME_ECS_AVAT';
  BUFFER_MUTEX_NAME  = 'BUFFER_MUTEX_ECS_AVAT';
  MONITOR_EVENT_NAME = 'MONITOR_EVENT_ECS_AVAT';
  CLIENT_EVENT_NAME  = 'CLIENT_EVENT_ECS_AVAT';

implementation


end.
 