
SELECT 
    A.*,
    (SELECT CODE_NAME FROM HITEMS_CODE_GROUP WHERE GRP_NO LIKE A.RST_CODE) RST_CODE_NAME,
    (SELECT NAME_KOR FROM HITEMS_USER WHERE USERID LIKE A.RST_BY) USER_NAME,
    (SELECT DESCR FROM HITEMS_USER AA, HITEMS_USER_GRADE BB WHERE AA.USERID LIKE A.RST_BY AND AA.GRADE = BB.GRADE) GRADE  
FROM 
( 
    SELECT A.*, B.RST_BY, RST_MH, RST_TIME_TYPE FROM TMS_RESULT A, TMS_RESULT_MH B
    WHERE A.RST_NO = B.RST_NO
) A
WHERE RST_PERFORM = '2013-09-26' 
AND RST_TIME_TYPE = 1;

SELECT 
    AB.*,
    (SELECT SUM(RST_MH) FROM TMS_RESULT A, TMS_RESULT_MH B WHERE A.RST_NO = B.RST_NO AND A.RST_PERFORM = AB.RST_PERFORM AND B.RST_BY LIKE AB.RST_BY AND RST_TIME_TYPE = AB.RST_TIME_TYPE) MH
FROM
(
    SELECT 
        RST_TIME_TYPE, A.RST_PERFORM, A.RST_NO, PRIV, POSITION, GRADE, DEPT_CD TEAM, A.RST_BY, NAME_KOR, DESCR, EOT, RST_TITLE, RST_CODE, RST_CODE_NAME, PLAN_NO, PLAN_REV_NO,
        (SELECT ENG_PROJNO FROM TMS_PLAN WHERE PLAN_NO LIKE A.PLAN_NO AND PLAN_REV_NO = A.PLAN_REV_NO) PROJNO,
        (SELECT ENG_TYPE FROM TMS_PLAN WHERE PLAN_NO LIKE A.PLAN_NO AND PLAN_REV_NO = A.PLAN_REV_NO) ENG_TYPE
    FROM
    (
        SELECT RST_TIME_TYPE, A.RST_PERFORM,  A.RST_NO, A.RST_BY, RST_TITLE, RST_CODE, RST_CODE_NAME, PLAN_NO, PLAN_REV_NO FROM
        (
            SELECT RST_PERFORM, MAX(RST_NO) RST_NO, RST_BY, RST_TIME_TYPE
            FROM
            (
                SELECT A.*, B.RST_BY, B.RST_TIME_TYPE FROM TMS_RESULT A, TMS_RESULT_MH B
                WHERE A.RST_NO = B.RST_NO
                AND RST_TIME_TYPE = 1
            )  
            GROUP BY RST_PERFORM, RST_BY, RST_TIME_TYPE
        ) A JOIN 
        (
            SELECT A.*, B.CODE_NAME RST_CODE_NAME FROM TMS_RESULT A, HITEMS_CODE_GROUP B
            WHERE A.RST_CODE = B.GRP_NO
        ) 
        B ON A.RST_NO = B.RST_NO
    ) A JOIN
    (
        SELECT A.USERID, PRIV, POSITION, A.GRADE, DEPT_CD, NAME_KOR, B.DESCR, EOT FROM HITEMS_USER A, HITEMS_USER_GRADE B
        WHERE A.GRADE = B.GRADE
    ) B
    ON A.RST_BY = B.USERID
) AB 
WHERE RST_PERFORM = '2013-09-26'        
                
