Create Table TMS_WORK_LDS_DATA
(
LDS_NO      VARCHAR2(20CHAR),
DATA1      NUMBER    DEFAULT 0,
DATA2      NUMBER    DEFAULT 0,
DATA3      NUMBER    DEFAULT 0,
DATA4      NUMBER    DEFAULT 0,
DATA5      NUMBER    DEFAULT 0,
DATA6      NUMBER    DEFAULT 0,
DATA7      NUMBER    DEFAULT 0,
DATA8      NUMBER    DEFAULT 0,
DATA9      NUMBER    DEFAULT 0,
DATA10      NUMBER    DEFAULT 0,
DATA11      NUMBER    DEFAULT 0,
DATA12      NUMBER    DEFAULT 0,
DATA13      NUMBER    DEFAULT 0,
DATA14      NUMBER    DEFAULT 0,
DATA15      NUMBER    DEFAULT 0,
DATA16      NUMBER    DEFAULT 0,
DATA17      NUMBER    DEFAULT 0,
DATA18      NUMBER    DEFAULT 0,
DATA19      NUMBER    DEFAULT 0,
DATA20      NUMBER    DEFAULT 0,
DATA21      NUMBER    DEFAULT 0,
DATA22      NUMBER    DEFAULT 0,
DATA23      NUMBER    DEFAULT 0,
DATA24      NUMBER    DEFAULT 0,
DATA25      NUMBER    DEFAULT 0,
DATA26      NUMBER    DEFAULT 0,
DATA27      NUMBER    DEFAULT 0,
DATA28      NUMBER    DEFAULT 0,
DATA29      NUMBER    DEFAULT 0,
DATA30      NUMBER    DEFAULT 0,
DATA31      NUMBER    DEFAULT 0,
DATA32      NUMBER    DEFAULT 0,
DATA33      NUMBER    DEFAULT 0,
DATA34      NUMBER    DEFAULT 0,
DATA35      NUMBER    DEFAULT 0,
DATA36      NUMBER    DEFAULT 0,
DATA37      NUMBER    DEFAULT 0,
DATA38      NUMBER    DEFAULT 0,
DATA39      NUMBER    DEFAULT 0,
DATA40      NUMBER    DEFAULT 0,
DATA41      NUMBER    DEFAULT 0,
DATA42      NUMBER    DEFAULT 0,
DATA43      NUMBER    DEFAULT 0,
DATA44      NUMBER    DEFAULT 0,
DATA45      NUMBER    DEFAULT 0,
DATA46      NUMBER    DEFAULT 0,
DATA47      NUMBER    DEFAULT 0,
DATA48      NUMBER    DEFAULT 0,
DATA49      NUMBER    DEFAULT 0,
DATA50      NUMBER    DEFAULT 0,
DATA51      NUMBER    DEFAULT 0,
DATA52      NUMBER    DEFAULT 0,
DATA53      NUMBER    DEFAULT 0,
DATA54      NUMBER    DEFAULT 0,
DATA55      NUMBER    DEFAULT 0,
DATA56      NUMBER    DEFAULT 0,
DATA57      NUMBER    DEFAULT 0,
DATA58      NUMBER    DEFAULT 0,
DATA59      NUMBER    DEFAULT 0,
DATA60      NUMBER    DEFAULT 0,
DATA61      NUMBER    DEFAULT 0,
DATA62      NUMBER    DEFAULT 0,
DATA63      NUMBER    DEFAULT 0,
DATA64      NUMBER    DEFAULT 0,
DATA65      NUMBER    DEFAULT 0,
DATA66      NUMBER    DEFAULT 0,
DATA67      NUMBER    DEFAULT 0,
DATA68      NUMBER    DEFAULT 0,
DATA69      NUMBER    DEFAULT 0,
DATA70      NUMBER    DEFAULT 0,
DATA71      NUMBER    DEFAULT 0,
DATA72      NUMBER    DEFAULT 0,
DATA73      NUMBER    DEFAULT 0,
DATA74      NUMBER    DEFAULT 0,
DATA75      NUMBER    DEFAULT 0,
DATA76      NUMBER    DEFAULT 0,
DATA77      NUMBER    DEFAULT 0,
DATA78      NUMBER    DEFAULT 0,
DATA79      NUMBER    DEFAULT 0,
DATA80      NUMBER    DEFAULT 0,
DATA81      NUMBER    DEFAULT 0,
DATA82      NUMBER    DEFAULT 0,
DATA83      NUMBER    DEFAULT 0,
DATA84      NUMBER    DEFAULT 0,
DATA85      NUMBER    DEFAULT 0,
DATA86      NUMBER    DEFAULT 0,
DATA87      NUMBER    DEFAULT 0,
DATA88      NUMBER    DEFAULT 0,
DATA89      NUMBER    DEFAULT 0,
DATA90      NUMBER    DEFAULT 0,
DATA91      NUMBER    DEFAULT 0,
DATA92      NUMBER    DEFAULT 0,
DATA93      NUMBER    DEFAULT 0,
DATA94      NUMBER    DEFAULT 0,
DATA95      NUMBER    DEFAULT 0,
DATA96      NUMBER    DEFAULT 0,
DATA97      NUMBER    DEFAULT 0,
DATA98      NUMBER    DEFAULT 0,
DATA99      NUMBER    DEFAULT 0,
DATA100      NUMBER    DEFAULT 0,
DATA101      NUMBER    DEFAULT 0,
DATA102      NUMBER    DEFAULT 0,
DATA103      NUMBER    DEFAULT 0,
DATA104      NUMBER    DEFAULT 0,
DATA105      NUMBER    DEFAULT 0,
DATA106      NUMBER    DEFAULT 0,
DATA107      NUMBER    DEFAULT 0,
DATA108      NUMBER    DEFAULT 0,
DATA109      NUMBER    DEFAULT 0,
DATA110      NUMBER    DEFAULT 0,
DATA111      NUMBER    DEFAULT 0,
DATA112      NUMBER    DEFAULT 0,
DATA113      NUMBER    DEFAULT 0,
DATA114      NUMBER    DEFAULT 0,
DATA115      NUMBER    DEFAULT 0,
DATA116      NUMBER    DEFAULT 0,
DATA117      NUMBER    DEFAULT 0,
DATA118      NUMBER    DEFAULT 0,
DATA119      NUMBER    DEFAULT 0,
DATA120      NUMBER    DEFAULT 0,
DATA121      NUMBER    DEFAULT 0,
DATA122      NUMBER    DEFAULT 0,
DATA123      NUMBER    DEFAULT 0,
DATA124      NUMBER    DEFAULT 0,
DATA125      NUMBER    DEFAULT 0,
DATA126      NUMBER    DEFAULT 0,
DATA127      NUMBER    DEFAULT 0,
DATA128      NUMBER    DEFAULT 0,
DATA129      NUMBER    DEFAULT 0,
DATA130      NUMBER    DEFAULT 0

);

COMMENT ON COLUMN TMS_WORK_LDS_DATA.LDS_NO  IS  'LDS_NUMBER';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA1  IS  'Exhaust Gas Temperature before Turbocharge ';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA2  IS  'Exhaust Gas Temperature Cylinder A1';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA3  IS  'Exhaust Gas Temperature Cylinder A2';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA4  IS  'Exhaust Gas Temperature Cylinder A3';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA5  IS  'Exhaust Gas Temperature Cylinder A4';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA6  IS  'Exhaust Gas Temperature Cylinder A5';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA7  IS  'Exhaust Gas Temperature Cylinder A6';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA8  IS  'Exhaust Gas Temperature Cylinder A7';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA9  IS  'Exhaust Gas Temperature Cylinder A8';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA10  IS  'Exhaust Gas Temperature Cylinder A9';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA11  IS  'Exhaust Gas Temperature Cylinder A10';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA12  IS  'Exhaust Gas Temperature after Turbocharge A';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA13  IS  'Exhaust Gas Temperature before Turbocharge ';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA14  IS  'Exhaust Gas Temperature Cylinder B1';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA15  IS  'Exhaust Gas Temperature Cylinder B2';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA16  IS  'Exhaust Gas Temperature Cylinder B3';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA17  IS  'Exhaust Gas Temperature Cylinder B4';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA18  IS  'Exhaust Gas Temperature Cylinder B5';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA19  IS  'Exhaust Gas Temperature Cylinder B6';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA20  IS  'Exhaust Gas Temperature Cylinder B7';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA21  IS  'Exhaust Gas Temperature Cylinder B8';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA22  IS  'Exhaust Gas Temperature Cylinder B9';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA23  IS  'Exhaust Gas Temperature Cylinder B10';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA24  IS  'Exhaust Gas Temperature after Turbocharge B';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA25  IS  'Main bearing Temperature 1';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA26  IS  'Main bearing Temperature 2';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA27  IS  'Main bearing Temperature 3';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA28  IS  'Main bearing Temperature 4';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA29  IS  'Main bearing Temperature 5';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA30  IS  'Main bearing Temperature 6';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA31  IS  'Main bearing Temperature 7';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA32  IS  'Main bearing Temperature 8';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA33  IS  'Main bearing Temperature 9';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA34  IS  'Main bearing Temperature 10';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA35  IS  'Main bearing Temperature 11';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA36  IS  'RPM_ENGINE';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA37  IS  'RPM_TC_A';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA38  IS  'RPM_TC_B';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA39  IS  'GEN_POWER';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA40  IS  'GEN_VOLTAGE';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA41  IS  'GETN_CURRENT';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA42  IS  'PRESSURE_CHARGE_AIR';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA43  IS  'PRESSURE_LT_ENGINE_INLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA44  IS  'PRESSURE_HT_ENGINE_INLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA45  IS  'PRESSURE_LO_FILTER_INLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA46  IS  'PRESSURE_LO_ENGINE_INLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA47  IS  'PRESSURE_LO_TC_A_INLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA48  IS  'PRESSURE_LO_TC_B_INLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA49  IS  'PRESSURE_FO_ENGINE_INLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA50  IS  'PRESSURE_CRANK_CASE_CHAMBER';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA51  IS  'TEMP_AIR_FLOW_NOZZLE';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA52  IS  'TEMP_COMP_INLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA53  IS  'TEMP_COMP_OUTLER';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA54  IS  'TEMP_AIR_BOX';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA55  IS  'TEMP_CHARGE_AIR';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA56  IS  'TEMP_LT_ENGINE_INLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA57  IS  'TEMP_LT_AIR_COOLER_INLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA58  IS  'TEMP_LT_ENGINE_OUTLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA59  IS  'TEMP_LT_ENGINE_INLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA60  IS  'TEMP_CYLINDER_INLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA61  IS  'TEMP_CYLINDER_OUTLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA62  IS  'TEMP_FO_ENGINE_INLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA63  IS  'TEMP_LO_ENGINE_INLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA64  IS  'GOV_INDICATOR';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA65  IS  'SMOKE_1';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA66  IS  'SMOKE_2';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA67  IS  'SMOKE_3';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA68  IS  'FUEL_MIN_1ST';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA69  IS  'FUEL_WEIGHT_1ST_1';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA70  IS  'FUEL_WEIGHT_1ST_2';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA71  IS  'FUEL_MFM_1ST_1';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA72  IS  'FUEL_MFM_1ST_2';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA73  IS  'FUEL_MIN_2ST';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA74  IS  'FUEL_WEIGHT_2ST_1';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA75  IS  'FUEL_WEIGHT_2ST_2';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA76  IS  'FUEL_MFM_2ST_1';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA77  IS  'FUEL_MFM_2ST_2';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA78  IS  'MANO_AIR_FLOW_METER';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA79  IS  'MANO_AIR_FLOW_METER_AMBIENT';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA80  IS  'MANO_TC_COMP_INLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA81  IS  'MANO_TC_COMP_INLET_AMBIENT';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA82  IS  'MANO_TC_COMP_OUTLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA83  IS  'MANO_TC_COMP_OUTLET_AIR_CHAMBER';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA84  IS  'MANO_AIR_BOX';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA85  IS  'MANO_AIR_BOX_AIR_CHAMBER';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA86  IS  'MANO_TURBINE_OUTLET';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA87  IS  'MANO_TURBINE_OUTLET_AMBIENT';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA88  IS  'AMBIENT_TEMP';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA89  IS  'AMBIENT_PRESSURE';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA90  IS  'AMBIENT_HYGRO';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA91  IS  'FUEL_INDEX_A_1';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA92  IS  'FUEL_INDEX_A_2';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA93  IS  'FUEL_INDEX_A_3';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA94  IS  'FUEL_INDEX_A_4';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA95  IS  'FUEL_INDEX_A_5';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA96  IS  'FUEL_INDEX_A_6';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA97  IS  'FUEL_INDEX_A_7';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA98  IS  'FUEL_INDEX_A_8';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA99  IS  'FUEL_INDEX_A_9';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA100  IS  'FUEL_INDEX_A_10';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA101  IS  'FUEL_INDEX_B_1';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA102  IS  'FUEL_INDEX_B_2';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA103  IS  'FUEL_INDEX_B_3';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA104  IS  'FUEL_INDEX_B_4';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA105  IS  'FUEL_INDEX_B_5';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA106  IS  'FUEL_INDEX_B_6';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA107  IS  'FUEL_INDEX_B_7';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA108  IS  'FUEL_INDEX_B_8';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA109  IS  'FUEL_INDEX_B_9';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA110  IS  'FUEL_INDEX_B_10';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA111  IS  'PMAX_A_1';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA112  IS  'PMAX_A_2';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA113  IS  'PMAX_A_3';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA114  IS  'PMAX_A_4';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA115  IS  'PMAX_A_5';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA116  IS  'PMAX_A_6';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA117  IS  'PMAX_A_7';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA118  IS  'PMAX_A_8';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA119  IS  'PMAX_A_9';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA120  IS  'PMAX_A_10';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA121  IS  'PMAX_B_1';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA122  IS  'PMAX_B_2';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA123  IS  'PMAX_B_3';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA124  IS  'PMAX_B_4';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA125  IS  'PMAX_B_5';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA126  IS  'PMAX_B_6';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA127  IS  'PMAX_B_7';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA128  IS  'PMAX_B_8';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA129  IS  'PMAX_B_9';
COMMENT ON COLUMN TMS_WORK_LDS_DATA.DATA130  IS  'PMAX_B_10';
