CREATE TABLE CABLE_SPEC
(
  CABLETYPE  VARCHAR2(20 CHAR)                  NOT NULL,
  SYMBOL     VARCHAR2(10 CHAR)                  NOT NULL,
  RATING_A   VARCHAR2(10 CHAR),
  O_D_MM     VARCHAR2(10 CHAR),
  TOL_MM     VARCHAR2(10 CHAR),
  JIS_GLAND  VARCHAR2(10 CHAR),
  DIN_GLAND  VARCHAR2(10 CHAR),
  REG_DATE   DATE
)