CREATE TABLE SENSOR_CODE
(
  SENSORCODE         NUMBER          NOT NULL,
  DRAWNO             VARCHAR2(30 CHAR),
  MAKER              VARCHAR2(30 CHAR),
  SENSORLENGTH       NUMBER,
  SENSORLENGTH_UNIT  VARCHAR2(5 CHAR),
  HOLESIZE           NUMBER,
  HOLESIZE_UNIT      VARCHAR2(5 CHAR),
  CABLELENGTH        NUMBER,
  CABLELENGTH_UNIT   VARCHAR2(5 CHAR),
  VALUE_UNIT         VARCHAR2(5 CHAR),
  SIGNALTYPE         VARCHAR2(10 CHAR),
  AREA               NUMBER,
  REG_DATE           DATE
)