CREATE TABLE THREAD_SPEC
(
  THREADTYPE      VARCHAR2(10 CHAR)             NOT NULL,
  THREADNAME      VARCHAR2(10 CHAR)             NOT NULL,
  MAJOR_DIA_INCH  VARCHAR2(10 CHAR),
  MAJOR_DIA_MM    VARCHAR2(10 CHAR),
  PITCH_MM        VARCHAR2(10 CHAR),
  DESCRIPTION     VARCHAR2(100 CHAR),
  REG_DATE        DATE
)