unit ModbusComConst;

interface

uses Messages, Graphics;

Const
  INIFILENAME = '.\EngMonitor.ini';
  SAVEINIFILENAME = 'SaveData.ini';
  MODBUS_SECTION = 'MODBUS';
  IPCCLIENTNAME1 = 'ModBusCom';
  IPCCLIENTNAME2 = 'ModBusCom2';
  WM_RECEIVESTRING = WM_USER + 100;
  WM_MODBUSDATA = WM_USER + 101;
  WM_MODBUSDATA2 = WM_USER + 102;
  WM_RECEIVEBYTE = WM_USER + 103;
  WM_SAVEDATA = WM_USER + 104;
  WM_INITCOMPORTERROR = WM_USER + 105;
  MODBUS_DATA_RTU_START_HI_IDX = 3;
  MODBUS_DATA_ASCII_START_HI_IDX = 8;
  MODBUS_DATA_ASCII_START_LO_IDX = 10;

  FILE_SEPERATOR = ',';
  COLOR_ON = clRed;
  COLOR_OFF = clLime;
  
Type
  TModBusMode = (ASCII_MODE, RTU_MODE);
  
implementation

end.
 