// Do not edit. This file is machine generated by the Resource DLL Wizard.

library DPMS_Login;

{ITE} {DFMFileType} {Forms\DataModule_Unit.dfm}
{ITE} {DFMFileType} {Forms\main_Form\appGrant_Unit.dfm}
{ITE} {DFMFileType} {Forms\main_Form\detailUser_Unit.dfm}
{ITE} {DFMFileType} {Forms\main_Form\login_Unit.dfm}
{ITE} {DFMFileType} {Forms\main_Form\main_Unit.dfm}
{ITE} {DFMFileType} {Forms\main_Form\newUser_Unit.dfm}
{ITE} {RCFileType} {E\pjh\project\util\HiTEMS_CBY\00.HiTEMS_CBY_\Source\bin\DPMS_Login_DRC.rc}

{$R 'Forms\DataModule_Unit.dfm' DM1:TDataModule}
{$R 'Forms\main_Form\appGrant_Unit.dfm' appGrant_Frm:TForm}
{$R 'Forms\main_Form\detailUser_Unit.dfm' detailUser_Frm:TForm}
{$R 'Forms\main_Form\login_Unit.dfm' login_Frm:TForm}
{$R 'Forms\main_Form\main_Unit.dfm' main_Frm:TForm}
{$R 'Forms\main_Form\newUser_Unit.dfm' newUser_Frm:TForm}
{$R 'E\pjh\project\util\HiTEMS_CBY\00.HiTEMS_CBY_\Source\bin\DPMS_Login_DRC.res' 'E\pjh\project\util\HiTEMS_CBY\00.HiTEMS_CBY_\Source\bin\DPMS_Login_DRC.rc'}

{$E ENU}

begin
end.
