unit TestMathClass;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, TestExtensions, SysUtils,MathClass;

type
  // Test methods for class TMath

  TestTMath = class(TTestCase)
  strict private
    FMath: TMath;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestAdd;
    procedure TestDivide;
    procedure TestMultiply;
    procedure TestSubtract;
    procedure TestDoubleIt;
    procedure TestTruncate;
    procedure TestDivideByZero;
  end;

implementation

procedure TestTMath.SetUp;
begin
  FMath := TMath.Create;
end;

procedure TestTMath.TearDown;
begin
  FMath.Free;
  FMath := nil;
end;

procedure TestTMath.TestAdd;
var
  Value: Double;
begin
  FMath.Value := 10;
  Value := 10;
  FMath.Add(Value);
  CheckEquals(20,FMath.Value);
end;

procedure TestTMath.TestDivide;
var
  Value: Double;
begin
  FMath.Value := 10;
  Value := 2;
  FMath.Divide(Value);
  CheckEquals(5,FMath.Value);
end;

procedure TestTMath.TestDivideByZero;
begin
   ExpectedException := EZeroDivide;
   FMath.Value := 10;
   FMath.Divide(0);
end;

procedure TestTMath.TestMultiply;
var
  Value: Double;
begin
  FMath.Value := 10;
  Value := 10;
  FMath.Multiply(Value);
  CheckEquals(100,FMath.Value);
end;

procedure TestTMath.TestSubtract;
var
  Value: Double;
begin
  FMath.Value := 10;
  Value := 10;
  FMath.Subtract(Value);
  CheckEquals(0,FMath.Value);
end;

procedure TestTMath.TestDoubleIt;
begin
  FMath.Value := 5;
  FMath.DoubleIt;
  CheckEquals(10,FMath.Value);
end;

procedure TestTMath.TestTruncate;
begin
  FMath.Value := 10.5;
  FMath.Truncate;
  CheckEquals(10,FMath.Value);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTMath.Suite);
  RegisterTest(TRepeatedTest.Create(TestTMath.Suite,5));
end.

