program ABCView;

uses
  Forms,
  NativeXml,
  Windows,
  Expanders in 'Source\Expanders.pas',
  FileThreads in 'Source\FileThreads.pas',
  Filters in 'Source\Filters.pas',
  ThreadedFilters in 'Source\ThreadedFilters.pas',
  Duplicates in 'Source\Duplicates.pas',
  Zipfiles in 'source\Zipfiles.pas',
  ImageProcessors in 'Source\ImageProcessors.pas',
  ItemLists in 'Source\ItemLists.pas',
  LossLess in 'Source\LossLess.pas',
  sdItems in 'Source\sdItems.pas',
  sdGraphicLoader in 'Source\sdGraphicLoader.pas',
  sdViewCanonCRW in '..\..\simlib\formats2D\sdViewCanonCRW.pas',
  sdRoots in 'source\sdRoots.pas',
  sdScanFolders in 'source\sdScanFolders.pas',
  sdProperties in 'source\sdProperties.pas',
  sdAbcTypes in 'source\sdAbcTypes.pas',
  sdAbcVars in 'source\sdAbcVars.pas',
  sdAbcFunctions in 'source\sdAbcFunctions.pas',
  sdApplicationOptions in 'source\sdApplicationOptions.pas',
  sdProcessThread in 'source\sdProcessThread.pas',
  DropLists in 'source\DropLists.pas',
  BrowseTrees in 'source\BrowseTrees.pas',
  sdSorter in 'source\sdSorter.pas',
  PixRefs in 'source\PixRefs.pas',
  Compares in 'source\Compares.pas',
  Thumbnails in 'source\Thumbnails.pas',
  Columns in 'source\Columns.pas',
  UserActivities in 'source\UserActivities.pas',
  Pictures in 'source\Pictures.pas',
  Links in 'source\Links.pas',
  OptionsManagers in 'Source\OptionsManagers.pas',
  Slideshows in 'source\Slideshows.pas',
  encrypt in 'source\encrypt.pas',
  ThumbItems in 'source\ThumbItems.pas',
  Filers in 'source\Filers.pas',
  ExportCSVs in 'source\ExportCSVs.pas',
  ExportXMLs in 'source\ExportXMLs.pas',
  CloseMatches in 'source\CloseMatches.pas',
  CopyFiles in 'source\CopyFiles.pas',
  guiMain in 'Source\guiMain.pas' {frmMain},
  guiRootItems in 'source\guiRootItems.pas' {RootFrame: TFrame},
  guiSelectionItems in 'source\guiSelectionItems.pas' {SelectionFrame: TFrame},
  guiActions in 'Source\guiActions.pas' {dmActions: TDataModule},
  guiBrowser in 'Source\guiBrowser.pas' {Browser: TFrame},
  guiEmail in 'Source\guiEmail.pas' {frmEmail},
  guiFeedback in 'Source\guiFeedback.pas' {Feedback},
  guiFilterDialog in 'Source\guiFilterDialog.pas' {dlgFilter},
  guiFilterFrame in 'Source\guiFilterFrame.pas' {FilterFrame: TFrame},
  guiFolderOptions in 'Source\guiFolderOptions.pas' {frFolderOptions: TFrame},
  guiItemView in 'Source\guiItemView.pas' {ItemView: TFrame},
  guiPidlItems in 'Source\guiPidlItems.pas' {PidlFrame: TFrame},
  guiPluginFrames in 'Source\guiPluginFrames.pas' {frmPlugin: TFrame},
  guiProcess in 'Source\guiProcess.pas' {frmProcesses},
  guiPropertyDialog in 'Source\guiPropertyDialog.pas' {frmProps},
  guiShow in 'Source\guiShow.pas' {frmShow},
  guiViewer in 'Source\guiViewer.pas' {Viewer: TFrame},
  guiPlugins in 'Source\guiPlugins.pas' {dlgPlugin},
  guiChangeFileDate in 'source\guiChangeFileDate.pas' {frmChangeFiledate},
  guiPluginFuzzyItems in 'source\guiPluginFuzzyItems.pas' {PluginFuzzyFrame: TFrame},
  guiTipOfDay in 'source\guiTipOfDay.pas' {frmTipOfDay},
  guiSplashScreen in 'source\guiSplashScreen.pas' {frmSplash},
  guiTempMessages in 'source\guiTempMessages.pas' {dlgTempMessage},
  guiOptions in 'source\guiOptions.pas' {frmOptions},
  guiAbout in 'source\guiAbout.pas' {frmAbout},
  guiAddFolder in 'source\guiAddFolder.pas' {dlgAddFolder},
  guiRenameFiles in 'source\guiRenameFiles.pas' {frmRenameFiles},
  guiBuildWeb in 'source\guiBuildWeb.pas' {frmBuildWeb},
  guiWebpageItems in 'source\guiWebpageItems.pas' {WebpageFrame: TFrame},
  guiExportFormat in 'source\guiExportFormat.pas' {frmExport},
  guiCloseMatchItems in 'source\guiCloseMatchItems.pas' {CloseMatchFrame: TFrame},
  guiStandardItems in 'source\guiStandardItems.pas' {StandardFrame: TFrame},
  guiSearchItems in 'source\guiSearchItems.pas' {SearchFrame: TFrame},
  guiDuplicateItems in 'source\guiDuplicateItems.pas' {DupeFrame: TFrame},
  guiDeleteFile in 'source\guiDeleteFile.pas' {frmDeleteFiles},
  guiRotateExif in 'source\guiRotateExif.pas' {frmRotateExifOri},
  NativeJpg in '..\..\simlib\nativejpg\NativeJpg.pas',
  sdJpegImage in '..\..\simlib\nativejpg\sdJpegImage.pas',
  sdJpegCoder in '..\..\simlib\nativejpg\sdJpegCoder.pas',
  sdJpegTypes in '..\..\simlib\nativejpg\sdJpegTypes.pas',
  sdJpegBitstream in '..\..\simlib\nativejpg\sdJpegBitstream.pas',
  sdJpegHuffman in '..\..\simlib\nativejpg\sdJpegHuffman.pas',
  sdJpegMarkers in '..\..\simlib\nativejpg\sdJpegMarkers.pas',
  sdJpegLossless in '..\..\simlib\nativejpg\sdJpegLossless.pas',
  sdJpegDCT in '..\..\simlib\nativejpg\sdJpegDCT.pas',
  sdMetadataExif in '..\..\simlib\general\sdMetadataExif.pas',
  sdMetadata in '..\..\simlib\general\sdMetadata.pas',
  sdMetadataTiff in '..\..\simlib\general\sdMetadataTiff.pas',
  sdMetadataJpg in '..\..\simlib\general\sdMetadataJpg.pas',
  sdMetadataIptc in '..\..\simlib\general\sdMetadataIptc.pas',
  sdMetadataCiff in '..\..\simlib\general\sdMetadataCiff.pas',
  sdColorTransforms in '..\..\simlib\color\sdColorTransforms.pas',
  sdBitmapConversionWin in '..\..\simlib\bitmap\sdBitmapConversionWin.pas',
  sdMapIterator in '..\..\simlib\bitmap\sdMapIterator.pas',
  sdBitmapResize in '..\..\simlib\bitmap\sdBitmapResize.pas',
  sdStreamableData in '..\..\simlib\general\sdStreamableData.pas',
  sdSortedLists in '..\..\simlib\general\sdSortedLists.pas',
  sdOptionRefs in '..\..\simlib\general\sdOptionRefs.pas',
  ShellUtilities in '..\..\extlib\VET\ShellUtilities.pas',
  VETResources in '..\..\extlib\VET\VETResources.pas',
  MapiControl in '..\..\extlib\mapi\MapiControl.pas',
  HTMLLite in '..\..\extlib\HtmlLite7_6\package\HTMLLite.pas',
  LiteSubs in '..\..\extlib\HtmlLite7_6\package\LiteSubs.pas',
  litegif2 in '..\..\extlib\HtmlLite7_6\package\litegif2.pas',
  litegif1 in '..\..\extlib\HtmlLite7_6\package\litegif1.pas',
  LiteUn2 in '..\..\extlib\HtmlLite7_6\package\LiteUn2.pas',
  LiteSbs1 in '..\..\extlib\HtmlLite7_6\package\LiteSbs1.pas',
  LitePars in '..\..\extlib\HtmlLite7_6\package\LitePars.pas',
  LiteDith in '..\..\extlib\HtmlLite7_6\package\LiteDith.pas',
  kbShellNotify in '..\..\extlib\kbshellnotify\kbShellNotify.pas',
  kbsnPIDL in '..\..\extlib\kbshellnotify\kbsnPIDL.pas',
  gifimage in '..\..\extlib\Formats\GifImage\gifimage.pas',
  GraphicEx in '..\..\extlib\GraphicEx\GraphicEx.pas',
  GraphicColor in '..\..\extlib\GraphicEx\GraphicColor.pas',
  GraphicStrings in '..\..\extlib\GraphicEx\GraphicStrings.pas',
  GraphicCompression in '..\..\extlib\GraphicEx\GraphicCompression.pas',
  MZLib in '..\..\extlib\GraphicEx\MZLib.pas',
  SHFileOp in '..\..\extlib\disk\SHFileOp.pas',
  ehswhatsthis in '..\..\extlib\EHS\ehswhatsthis.pas',
  ehscontextmap in '..\..\extlib\EHS\ehscontextmap.pas',
  ehshshtb in '..\..\extlib\EHS\ehshshtb.pas',
  ehsbase in '..\..\extlib\EHS\ehsbase.pas',
  ehshelprouter in '..\..\extlib\EHS\ehshelprouter.pas',
  ehshhapi in '..\..\extlib\EHS\ehshhapi.pas',
  DropSource in '..\..\extlib\DragDrop_37\Components\DropSource.pas',
  DropTarget in '..\..\extlib\DragDrop_37\Components\DropTarget.pas',
  RxNotify in '..\..\extlib\rxlib275c\units\RxNotify.pas',
  rxFileUtil in '..\..\extlib\rxlib275c\units\rxFileUtil.pas',
  rxStrUtils in '..\..\extlib\rxlib275c\units\rxStrUtils.pas',
  Rxprgrss in '..\..\extlib\rxlib275c\units\Rxprgrss.pas',
  rxVclutils in '..\..\extlib\rxlib275c\units\rxVclutils.pas',
  Rxcconst in '..\..\extlib\rxlib275c\units\Rxcconst.pas',
  Rxconst in '..\..\extlib\rxlib275c\units\Rxconst.pas',
  rxMaxmin in '..\..\extlib\rxlib275c\units\rxMaxmin.pas',
  rxDateutil in '..\..\extlib\rxlib275c\units\rxDateutil.pas',
  RXSpin in '..\..\extlib\rxlib275c\units\RXSpin.pas',
  rxToolEdit in '..\..\extlib\rxlib275c\units\rxToolEdit.pas',
  RxCtrls in '..\..\extlib\rxlib275c\units\RxCtrls.pas',
  rxPlacemnt in '..\..\extlib\rxlib275c\units\rxPlacemnt.pas',
  Rxhook in '..\..\extlib\rxlib275c\units\Rxhook.pas',
  Rxprops in '..\..\extlib\rxlib275c\units\Rxprops.pas',
  rxApputils in '..\..\extlib\rxlib275c\units\rxApputils.pas',
  RxTimer in '..\..\extlib\rxlib275c\units\RxTimer.pas',
  rxPickdate in '..\..\extlib\rxlib275c\units\rxPickdate.pas',
  Rxslider in '..\..\extlib\rxlib275c\units\Rxslider.pas',
  Rxshell in '..\..\extlib\rxlib275c\units\Rxshell.pas',
  rxIcolist in '..\..\extlib\rxlib275c\units\rxIcolist.pas',
  rxAppevent in '..\..\extlib\rxlib275c\units\rxAppevent.pas',
  rxgrids in '..\..\extlib\rxlib275c\units\rxgrids.pas',
  Rxsplit in '..\..\extlib\rxlib275c\units\Rxsplit.pas',
  Rxgrdcpt in '..\..\extlib\rxlib275c\units\Rxgrdcpt.pas',
  rxSpeedbar in '..\..\extlib\rxlib275c\units\rxSpeedbar.pas',
  rxSbsetup in '..\..\extlib\rxlib275c\units\rxSbsetup.pas' {SpeedbarSetupWindow},
  Rxtconst in '..\..\extlib\rxlib275c\units\Rxtconst.pas',
  RxMemDS in '..\..\extlib\rxlib275c\units\RxMemDS.pas',
  rxDbutils in '..\..\extlib\rxlib275c\units\rxDbutils.pas',
  Rxdconst in '..\..\extlib\rxlib275c\units\Rxdconst.pas',
  RxCombos in '..\..\extlib\rxlib275c\units\RxCombos.pas',
  rrxcombo in '..\..\extlib\rxlib275c\units\rrxcombo.pas',
  rxAnimate in '..\..\extlib\rxlib275c\units\rxAnimate.pas',
  DiskInfo in '..\..\extlib\disk\DiskInfo.pas',
  ZipMstr in '..\..\extlib\zipmstr15\ZipMstr.pas',
  ShellUtils in '..\..\simlib\disk\ShellUtils.pas',
  Crc32 in '..\..\extlib\filters\other\Crc32.pas';

{$R *.RES}


begin

  Application.Initialize;
  Application.Title := 'ABC-View';

  // the first "component", from this moment there is debugging
  // capability
  Application.CreateForm(TDebugComponent, glDebugComponent);
  Application.CreateForm(TfrmMain, frmMain);
  // the debug component relays info to the main form where it can be visualized
  //glDebugComponent.OnDebugOut := frmMain.ComponentDebug;
  Application.CreateForm(TdlgFilter, dlgFilter);
  Application.CreateForm(TfrmProps, frmProps);
  Application.CreateForm(TfrmRotateExifOri, frmRotateExifOri);
  //frmRotateExifOri.OnDebugOut := frmMain.ComponentDebug;
  Application.Run;
end.
